/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DtoCreateTaxAssociationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateTaxAssociationRequest{}

// DtoCreateTaxAssociationRequest struct for DtoCreateTaxAssociationRequest
type DtoCreateTaxAssociationRequest struct {
	AutoApply *bool `json:"auto_apply,omitempty"`
	Currency *string `json:"currency,omitempty"`
	EntityId string `json:"entity_id"`
	EntityType TypesTaxRateEntityType `json:"entity_type"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	Priority *int32 `json:"priority,omitempty"`
	TaxRateCode string `json:"tax_rate_code"`
}

type _DtoCreateTaxAssociationRequest DtoCreateTaxAssociationRequest

// NewDtoCreateTaxAssociationRequest instantiates a new DtoCreateTaxAssociationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateTaxAssociationRequest(entityId string, entityType TypesTaxRateEntityType, taxRateCode string) *DtoCreateTaxAssociationRequest {
	this := DtoCreateTaxAssociationRequest{}
	this.EntityId = entityId
	this.EntityType = entityType
	this.TaxRateCode = taxRateCode
	return &this
}

// NewDtoCreateTaxAssociationRequestWithDefaults instantiates a new DtoCreateTaxAssociationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateTaxAssociationRequestWithDefaults() *DtoCreateTaxAssociationRequest {
	this := DtoCreateTaxAssociationRequest{}
	return &this
}

// GetAutoApply returns the AutoApply field value if set, zero value otherwise.
func (o *DtoCreateTaxAssociationRequest) GetAutoApply() bool {
	if o == nil || IsNil(o.AutoApply) {
		var ret bool
		return ret
	}
	return *o.AutoApply
}

// GetAutoApplyOk returns a tuple with the AutoApply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetAutoApplyOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoApply) {
		return nil, false
	}
	return o.AutoApply, true
}

// HasAutoApply returns a boolean if a field has been set.
func (o *DtoCreateTaxAssociationRequest) HasAutoApply() bool {
	if o != nil && !IsNil(o.AutoApply) {
		return true
	}

	return false
}

// SetAutoApply gets a reference to the given bool and assigns it to the AutoApply field.
func (o *DtoCreateTaxAssociationRequest) SetAutoApply(v bool) {
	o.AutoApply = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DtoCreateTaxAssociationRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DtoCreateTaxAssociationRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DtoCreateTaxAssociationRequest) SetCurrency(v string) {
	o.Currency = &v
}

// GetEntityId returns the EntityId field value
func (o *DtoCreateTaxAssociationRequest) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *DtoCreateTaxAssociationRequest) SetEntityId(v string) {
	o.EntityId = v
}

// GetEntityType returns the EntityType field value
func (o *DtoCreateTaxAssociationRequest) GetEntityType() TypesTaxRateEntityType {
	if o == nil {
		var ret TypesTaxRateEntityType
		return ret
	}

	return o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetEntityTypeOk() (*TypesTaxRateEntityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityType, true
}

// SetEntityType sets field value
func (o *DtoCreateTaxAssociationRequest) SetEntityType(v TypesTaxRateEntityType) {
	o.EntityType = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DtoCreateTaxAssociationRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DtoCreateTaxAssociationRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DtoCreateTaxAssociationRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *DtoCreateTaxAssociationRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *DtoCreateTaxAssociationRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *DtoCreateTaxAssociationRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetTaxRateCode returns the TaxRateCode field value
func (o *DtoCreateTaxAssociationRequest) GetTaxRateCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaxRateCode
}

// GetTaxRateCodeOk returns a tuple with the TaxRateCode field value
// and a boolean to check if the value has been set.
func (o *DtoCreateTaxAssociationRequest) GetTaxRateCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxRateCode, true
}

// SetTaxRateCode sets field value
func (o *DtoCreateTaxAssociationRequest) SetTaxRateCode(v string) {
	o.TaxRateCode = v
}

func (o DtoCreateTaxAssociationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateTaxAssociationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoApply) {
		toSerialize["auto_apply"] = o.AutoApply
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	toSerialize["entity_id"] = o.EntityId
	toSerialize["entity_type"] = o.EntityType
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	toSerialize["tax_rate_code"] = o.TaxRateCode
	return toSerialize, nil
}

func (o *DtoCreateTaxAssociationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_id",
		"entity_type",
		"tax_rate_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoCreateTaxAssociationRequest := _DtoCreateTaxAssociationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoCreateTaxAssociationRequest)

	if err != nil {
		return err
	}

	*o = DtoCreateTaxAssociationRequest(varDtoCreateTaxAssociationRequest)

	return err
}

type NullableDtoCreateTaxAssociationRequest struct {
	value *DtoCreateTaxAssociationRequest
	isSet bool
}

func (v NullableDtoCreateTaxAssociationRequest) Get() *DtoCreateTaxAssociationRequest {
	return v.value
}

func (v *NullableDtoCreateTaxAssociationRequest) Set(val *DtoCreateTaxAssociationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateTaxAssociationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateTaxAssociationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateTaxAssociationRequest(val *DtoCreateTaxAssociationRequest) *NullableDtoCreateTaxAssociationRequest {
	return &NullableDtoCreateTaxAssociationRequest{value: val, isSet: true}
}

func (v NullableDtoCreateTaxAssociationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateTaxAssociationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


