/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoSourceUsageItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoSourceUsageItem{}

// DtoSourceUsageItem struct for DtoSourceUsageItem
type DtoSourceUsageItem struct {
	// cost is the cost attributed to this source for the line item
	Cost *string `json:"cost,omitempty"`
	// event_count is the number of events from this source (optional)
	EventCount *int32 `json:"event_count,omitempty"`
	// percentage is the percentage of total line item cost from this source (optional)
	Percentage *string `json:"percentage,omitempty"`
	// source is the name of the event source
	Source *string `json:"source,omitempty"`
	// usage is the total usage amount from this source (optional, for additional context)
	Usage *string `json:"usage,omitempty"`
}

// NewDtoSourceUsageItem instantiates a new DtoSourceUsageItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoSourceUsageItem() *DtoSourceUsageItem {
	this := DtoSourceUsageItem{}
	return &this
}

// NewDtoSourceUsageItemWithDefaults instantiates a new DtoSourceUsageItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoSourceUsageItemWithDefaults() *DtoSourceUsageItem {
	this := DtoSourceUsageItem{}
	return &this
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *DtoSourceUsageItem) GetCost() string {
	if o == nil || IsNil(o.Cost) {
		var ret string
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSourceUsageItem) GetCostOk() (*string, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *DtoSourceUsageItem) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given string and assigns it to the Cost field.
func (o *DtoSourceUsageItem) SetCost(v string) {
	o.Cost = &v
}

// GetEventCount returns the EventCount field value if set, zero value otherwise.
func (o *DtoSourceUsageItem) GetEventCount() int32 {
	if o == nil || IsNil(o.EventCount) {
		var ret int32
		return ret
	}
	return *o.EventCount
}

// GetEventCountOk returns a tuple with the EventCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSourceUsageItem) GetEventCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EventCount) {
		return nil, false
	}
	return o.EventCount, true
}

// HasEventCount returns a boolean if a field has been set.
func (o *DtoSourceUsageItem) HasEventCount() bool {
	if o != nil && !IsNil(o.EventCount) {
		return true
	}

	return false
}

// SetEventCount gets a reference to the given int32 and assigns it to the EventCount field.
func (o *DtoSourceUsageItem) SetEventCount(v int32) {
	o.EventCount = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *DtoSourceUsageItem) GetPercentage() string {
	if o == nil || IsNil(o.Percentage) {
		var ret string
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSourceUsageItem) GetPercentageOk() (*string, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *DtoSourceUsageItem) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given string and assigns it to the Percentage field.
func (o *DtoSourceUsageItem) SetPercentage(v string) {
	o.Percentage = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DtoSourceUsageItem) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSourceUsageItem) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DtoSourceUsageItem) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *DtoSourceUsageItem) SetSource(v string) {
	o.Source = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *DtoSourceUsageItem) GetUsage() string {
	if o == nil || IsNil(o.Usage) {
		var ret string
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSourceUsageItem) GetUsageOk() (*string, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *DtoSourceUsageItem) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given string and assigns it to the Usage field.
func (o *DtoSourceUsageItem) SetUsage(v string) {
	o.Usage = &v
}

func (o DtoSourceUsageItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoSourceUsageItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.EventCount) {
		toSerialize["event_count"] = o.EventCount
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableDtoSourceUsageItem struct {
	value *DtoSourceUsageItem
	isSet bool
}

func (v NullableDtoSourceUsageItem) Get() *DtoSourceUsageItem {
	return v.value
}

func (v *NullableDtoSourceUsageItem) Set(val *DtoSourceUsageItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoSourceUsageItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoSourceUsageItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoSourceUsageItem(val *DtoSourceUsageItem) *NullableDtoSourceUsageItem {
	return &NullableDtoSourceUsageItem{value: val, isSet: true}
}

func (v NullableDtoSourceUsageItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoSourceUsageItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


