/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"fmt"
)

// TypesScheduledTaskEntityType the model 'TypesScheduledTaskEntityType'
type TypesScheduledTaskEntityType string

// List of types.ScheduledTaskEntityType
const (
	TYPESSCHEDULEDTASKENTITYTYPE_ScheduledTaskEntityTypeEvents TypesScheduledTaskEntityType = "events"
	TYPESSCHEDULEDTASKENTITYTYPE_ScheduledTaskEntityTypeInvoice TypesScheduledTaskEntityType = "invoice"
	TYPESSCHEDULEDTASKENTITYTYPE_ScheduledTaskEntityTypeCreditTopups TypesScheduledTaskEntityType = "credit_topups"
	TYPESSCHEDULEDTASKENTITYTYPE_ScheduledTaskEntityTypeCreditUsage TypesScheduledTaskEntityType = "credit_usage"
)

// All allowed values of TypesScheduledTaskEntityType enum
var AllowedTypesScheduledTaskEntityTypeEnumValues = []TypesScheduledTaskEntityType{
	"events",
	"invoice",
	"credit_topups",
	"credit_usage",
}

func (v *TypesScheduledTaskEntityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesScheduledTaskEntityType(value)
	for _, existing := range AllowedTypesScheduledTaskEntityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesScheduledTaskEntityType", value)
}

// NewTypesScheduledTaskEntityTypeFromValue returns a pointer to a valid TypesScheduledTaskEntityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesScheduledTaskEntityTypeFromValue(v string) (*TypesScheduledTaskEntityType, error) {
	ev := TypesScheduledTaskEntityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesScheduledTaskEntityType: valid values are %v", v, AllowedTypesScheduledTaskEntityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesScheduledTaskEntityType) IsValid() bool {
	for _, existing := range AllowedTypesScheduledTaskEntityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.ScheduledTaskEntityType value
func (v TypesScheduledTaskEntityType) Ptr() *TypesScheduledTaskEntityType {
	return &v
}

type NullableTypesScheduledTaskEntityType struct {
	value *TypesScheduledTaskEntityType
	isSet bool
}

func (v NullableTypesScheduledTaskEntityType) Get() *TypesScheduledTaskEntityType {
	return v.value
}

func (v *NullableTypesScheduledTaskEntityType) Set(val *TypesScheduledTaskEntityType) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesScheduledTaskEntityType) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesScheduledTaskEntityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesScheduledTaskEntityType(val *TypesScheduledTaskEntityType) *NullableTypesScheduledTaskEntityType {
	return &NullableTypesScheduledTaskEntityType{value: val, isSet: true}
}

func (v NullableTypesScheduledTaskEntityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesScheduledTaskEntityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

