/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"fmt"
)

// TypesProrationBehavior the model 'TypesProrationBehavior'
type TypesProrationBehavior string

// List of types.ProrationBehavior
const (
	TYPESPRORATIONBEHAVIOR_ProrationBehaviorCreateProrations TypesProrationBehavior = "create_prorations"
	TYPESPRORATIONBEHAVIOR_ProrationBehaviorNone TypesProrationBehavior = "none"
)

// All allowed values of TypesProrationBehavior enum
var AllowedTypesProrationBehaviorEnumValues = []TypesProrationBehavior{
	"create_prorations",
	"none",
}

func (v *TypesProrationBehavior) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesProrationBehavior(value)
	for _, existing := range AllowedTypesProrationBehaviorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesProrationBehavior", value)
}

// NewTypesProrationBehaviorFromValue returns a pointer to a valid TypesProrationBehavior
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesProrationBehaviorFromValue(v string) (*TypesProrationBehavior, error) {
	ev := TypesProrationBehavior(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesProrationBehavior: valid values are %v", v, AllowedTypesProrationBehaviorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesProrationBehavior) IsValid() bool {
	for _, existing := range AllowedTypesProrationBehaviorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.ProrationBehavior value
func (v TypesProrationBehavior) Ptr() *TypesProrationBehavior {
	return &v
}

type NullableTypesProrationBehavior struct {
	value *TypesProrationBehavior
	isSet bool
}

func (v NullableTypesProrationBehavior) Get() *TypesProrationBehavior {
	return v.value
}

func (v *NullableTypesProrationBehavior) Set(val *TypesProrationBehavior) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesProrationBehavior) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesProrationBehavior) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesProrationBehavior(val *TypesProrationBehavior) *NullableTypesProrationBehavior {
	return &NullableTypesProrationBehavior{value: val, isSet: true}
}

func (v NullableTypesProrationBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesProrationBehavior) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

