/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoCreditGrantApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreditGrantApplicationResponse{}

// DtoCreditGrantApplicationResponse struct for DtoCreditGrantApplicationResponse
type DtoCreditGrantApplicationResponse struct {
	ApplicationReason *TypesCreditGrantApplicationReason `json:"application_reason,omitempty"`
	ApplicationStatus *TypesApplicationStatus `json:"application_status,omitempty"`
	AppliedAt *string `json:"applied_at,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreditGrantId *string `json:"credit_grant_id,omitempty"`
	Credits *float32 `json:"credits,omitempty"`
	EnvironmentId *string `json:"environment_id,omitempty"`
	FailureReason *string `json:"failure_reason,omitempty"`
	Id *string `json:"id,omitempty"`
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	PeriodEnd *string `json:"period_end,omitempty"`
	PeriodStart *string `json:"period_start,omitempty"`
	RetryCount *int32 `json:"retry_count,omitempty"`
	ScheduledFor *string `json:"scheduled_for,omitempty"`
	Status *TypesStatus `json:"status,omitempty"`
	SubscriptionId *string `json:"subscription_id,omitempty"`
	SubscriptionStatusAtApplication *TypesSubscriptionStatus `json:"subscription_status_at_application,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
}

// NewDtoCreditGrantApplicationResponse instantiates a new DtoCreditGrantApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreditGrantApplicationResponse() *DtoCreditGrantApplicationResponse {
	this := DtoCreditGrantApplicationResponse{}
	return &this
}

// NewDtoCreditGrantApplicationResponseWithDefaults instantiates a new DtoCreditGrantApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreditGrantApplicationResponseWithDefaults() *DtoCreditGrantApplicationResponse {
	this := DtoCreditGrantApplicationResponse{}
	return &this
}

// GetApplicationReason returns the ApplicationReason field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetApplicationReason() TypesCreditGrantApplicationReason {
	if o == nil || IsNil(o.ApplicationReason) {
		var ret TypesCreditGrantApplicationReason
		return ret
	}
	return *o.ApplicationReason
}

// GetApplicationReasonOk returns a tuple with the ApplicationReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetApplicationReasonOk() (*TypesCreditGrantApplicationReason, bool) {
	if o == nil || IsNil(o.ApplicationReason) {
		return nil, false
	}
	return o.ApplicationReason, true
}

// HasApplicationReason returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasApplicationReason() bool {
	if o != nil && !IsNil(o.ApplicationReason) {
		return true
	}

	return false
}

// SetApplicationReason gets a reference to the given TypesCreditGrantApplicationReason and assigns it to the ApplicationReason field.
func (o *DtoCreditGrantApplicationResponse) SetApplicationReason(v TypesCreditGrantApplicationReason) {
	o.ApplicationReason = &v
}

// GetApplicationStatus returns the ApplicationStatus field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetApplicationStatus() TypesApplicationStatus {
	if o == nil || IsNil(o.ApplicationStatus) {
		var ret TypesApplicationStatus
		return ret
	}
	return *o.ApplicationStatus
}

// GetApplicationStatusOk returns a tuple with the ApplicationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetApplicationStatusOk() (*TypesApplicationStatus, bool) {
	if o == nil || IsNil(o.ApplicationStatus) {
		return nil, false
	}
	return o.ApplicationStatus, true
}

// HasApplicationStatus returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasApplicationStatus() bool {
	if o != nil && !IsNil(o.ApplicationStatus) {
		return true
	}

	return false
}

// SetApplicationStatus gets a reference to the given TypesApplicationStatus and assigns it to the ApplicationStatus field.
func (o *DtoCreditGrantApplicationResponse) SetApplicationStatus(v TypesApplicationStatus) {
	o.ApplicationStatus = &v
}

// GetAppliedAt returns the AppliedAt field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetAppliedAt() string {
	if o == nil || IsNil(o.AppliedAt) {
		var ret string
		return ret
	}
	return *o.AppliedAt
}

// GetAppliedAtOk returns a tuple with the AppliedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetAppliedAtOk() (*string, bool) {
	if o == nil || IsNil(o.AppliedAt) {
		return nil, false
	}
	return o.AppliedAt, true
}

// HasAppliedAt returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasAppliedAt() bool {
	if o != nil && !IsNil(o.AppliedAt) {
		return true
	}

	return false
}

// SetAppliedAt gets a reference to the given string and assigns it to the AppliedAt field.
func (o *DtoCreditGrantApplicationResponse) SetAppliedAt(v string) {
	o.AppliedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DtoCreditGrantApplicationResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *DtoCreditGrantApplicationResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreditGrantId returns the CreditGrantId field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetCreditGrantId() string {
	if o == nil || IsNil(o.CreditGrantId) {
		var ret string
		return ret
	}
	return *o.CreditGrantId
}

// GetCreditGrantIdOk returns a tuple with the CreditGrantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetCreditGrantIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreditGrantId) {
		return nil, false
	}
	return o.CreditGrantId, true
}

// HasCreditGrantId returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasCreditGrantId() bool {
	if o != nil && !IsNil(o.CreditGrantId) {
		return true
	}

	return false
}

// SetCreditGrantId gets a reference to the given string and assigns it to the CreditGrantId field.
func (o *DtoCreditGrantApplicationResponse) SetCreditGrantId(v string) {
	o.CreditGrantId = &v
}

// GetCredits returns the Credits field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetCredits() float32 {
	if o == nil || IsNil(o.Credits) {
		var ret float32
		return ret
	}
	return *o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetCreditsOk() (*float32, bool) {
	if o == nil || IsNil(o.Credits) {
		return nil, false
	}
	return o.Credits, true
}

// HasCredits returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasCredits() bool {
	if o != nil && !IsNil(o.Credits) {
		return true
	}

	return false
}

// SetCredits gets a reference to the given float32 and assigns it to the Credits field.
func (o *DtoCreditGrantApplicationResponse) SetCredits(v float32) {
	o.Credits = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetEnvironmentId() string {
	if o == nil || IsNil(o.EnvironmentId) {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentId) {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasEnvironmentId() bool {
	if o != nil && !IsNil(o.EnvironmentId) {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *DtoCreditGrantApplicationResponse) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetFailureReason returns the FailureReason field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetFailureReason() string {
	if o == nil || IsNil(o.FailureReason) {
		var ret string
		return ret
	}
	return *o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailureReason) {
		return nil, false
	}
	return o.FailureReason, true
}

// HasFailureReason returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasFailureReason() bool {
	if o != nil && !IsNil(o.FailureReason) {
		return true
	}

	return false
}

// SetFailureReason gets a reference to the given string and assigns it to the FailureReason field.
func (o *DtoCreditGrantApplicationResponse) SetFailureReason(v string) {
	o.FailureReason = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoCreditGrantApplicationResponse) SetId(v string) {
	o.Id = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *DtoCreditGrantApplicationResponse) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DtoCreditGrantApplicationResponse) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetPeriodEnd() string {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret string
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetPeriodEndOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given string and assigns it to the PeriodEnd field.
func (o *DtoCreditGrantApplicationResponse) SetPeriodEnd(v string) {
	o.PeriodEnd = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetPeriodStart() string {
	if o == nil || IsNil(o.PeriodStart) {
		var ret string
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetPeriodStartOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given string and assigns it to the PeriodStart field.
func (o *DtoCreditGrantApplicationResponse) SetPeriodStart(v string) {
	o.PeriodStart = &v
}

// GetRetryCount returns the RetryCount field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetRetryCount() int32 {
	if o == nil || IsNil(o.RetryCount) {
		var ret int32
		return ret
	}
	return *o.RetryCount
}

// GetRetryCountOk returns a tuple with the RetryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetRetryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryCount) {
		return nil, false
	}
	return o.RetryCount, true
}

// HasRetryCount returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasRetryCount() bool {
	if o != nil && !IsNil(o.RetryCount) {
		return true
	}

	return false
}

// SetRetryCount gets a reference to the given int32 and assigns it to the RetryCount field.
func (o *DtoCreditGrantApplicationResponse) SetRetryCount(v int32) {
	o.RetryCount = &v
}

// GetScheduledFor returns the ScheduledFor field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetScheduledFor() string {
	if o == nil || IsNil(o.ScheduledFor) {
		var ret string
		return ret
	}
	return *o.ScheduledFor
}

// GetScheduledForOk returns a tuple with the ScheduledFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetScheduledForOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledFor) {
		return nil, false
	}
	return o.ScheduledFor, true
}

// HasScheduledFor returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasScheduledFor() bool {
	if o != nil && !IsNil(o.ScheduledFor) {
		return true
	}

	return false
}

// SetScheduledFor gets a reference to the given string and assigns it to the ScheduledFor field.
func (o *DtoCreditGrantApplicationResponse) SetScheduledFor(v string) {
	o.ScheduledFor = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetStatus() TypesStatus {
	if o == nil || IsNil(o.Status) {
		var ret TypesStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetStatusOk() (*TypesStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TypesStatus and assigns it to the Status field.
func (o *DtoCreditGrantApplicationResponse) SetStatus(v TypesStatus) {
	o.Status = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *DtoCreditGrantApplicationResponse) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetSubscriptionStatusAtApplication returns the SubscriptionStatusAtApplication field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetSubscriptionStatusAtApplication() TypesSubscriptionStatus {
	if o == nil || IsNil(o.SubscriptionStatusAtApplication) {
		var ret TypesSubscriptionStatus
		return ret
	}
	return *o.SubscriptionStatusAtApplication
}

// GetSubscriptionStatusAtApplicationOk returns a tuple with the SubscriptionStatusAtApplication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetSubscriptionStatusAtApplicationOk() (*TypesSubscriptionStatus, bool) {
	if o == nil || IsNil(o.SubscriptionStatusAtApplication) {
		return nil, false
	}
	return o.SubscriptionStatusAtApplication, true
}

// HasSubscriptionStatusAtApplication returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasSubscriptionStatusAtApplication() bool {
	if o != nil && !IsNil(o.SubscriptionStatusAtApplication) {
		return true
	}

	return false
}

// SetSubscriptionStatusAtApplication gets a reference to the given TypesSubscriptionStatus and assigns it to the SubscriptionStatusAtApplication field.
func (o *DtoCreditGrantApplicationResponse) SetSubscriptionStatusAtApplication(v TypesSubscriptionStatus) {
	o.SubscriptionStatusAtApplication = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DtoCreditGrantApplicationResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DtoCreditGrantApplicationResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *DtoCreditGrantApplicationResponse) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantApplicationResponse) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *DtoCreditGrantApplicationResponse) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *DtoCreditGrantApplicationResponse) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

func (o DtoCreditGrantApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreditGrantApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationReason) {
		toSerialize["application_reason"] = o.ApplicationReason
	}
	if !IsNil(o.ApplicationStatus) {
		toSerialize["application_status"] = o.ApplicationStatus
	}
	if !IsNil(o.AppliedAt) {
		toSerialize["applied_at"] = o.AppliedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.CreditGrantId) {
		toSerialize["credit_grant_id"] = o.CreditGrantId
	}
	if !IsNil(o.Credits) {
		toSerialize["credits"] = o.Credits
	}
	if !IsNil(o.EnvironmentId) {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	if !IsNil(o.FailureReason) {
		toSerialize["failure_reason"] = o.FailureReason
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["period_end"] = o.PeriodEnd
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["period_start"] = o.PeriodStart
	}
	if !IsNil(o.RetryCount) {
		toSerialize["retry_count"] = o.RetryCount
	}
	if !IsNil(o.ScheduledFor) {
		toSerialize["scheduled_for"] = o.ScheduledFor
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if !IsNil(o.SubscriptionStatusAtApplication) {
		toSerialize["subscription_status_at_application"] = o.SubscriptionStatusAtApplication
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	return toSerialize, nil
}

type NullableDtoCreditGrantApplicationResponse struct {
	value *DtoCreditGrantApplicationResponse
	isSet bool
}

func (v NullableDtoCreditGrantApplicationResponse) Get() *DtoCreditGrantApplicationResponse {
	return v.value
}

func (v *NullableDtoCreditGrantApplicationResponse) Set(val *DtoCreditGrantApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreditGrantApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreditGrantApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreditGrantApplicationResponse(val *DtoCreditGrantApplicationResponse) *NullableDtoCreditGrantApplicationResponse {
	return &NullableDtoCreditGrantApplicationResponse{value: val, isSet: true}
}

func (v NullableDtoCreditGrantApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreditGrantApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


