/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoDebugTracker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoDebugTracker{}

// DtoDebugTracker struct for DtoDebugTracker
type DtoDebugTracker struct {
	CustomerLookup *DtoCustomerLookupResult `json:"customer_lookup,omitempty"`
	FailurePoint *TypesFailurePoint `json:"failure_point,omitempty"`
	MeterMatching *DtoMeterMatchingResult `json:"meter_matching,omitempty"`
	PriceLookup *DtoPriceLookupResult `json:"price_lookup,omitempty"`
	SubscriptionLineItemLookup *DtoSubscriptionLineItemLookupResult `json:"subscription_line_item_lookup,omitempty"`
}

// NewDtoDebugTracker instantiates a new DtoDebugTracker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoDebugTracker() *DtoDebugTracker {
	this := DtoDebugTracker{}
	return &this
}

// NewDtoDebugTrackerWithDefaults instantiates a new DtoDebugTracker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoDebugTrackerWithDefaults() *DtoDebugTracker {
	this := DtoDebugTracker{}
	return &this
}

// GetCustomerLookup returns the CustomerLookup field value if set, zero value otherwise.
func (o *DtoDebugTracker) GetCustomerLookup() DtoCustomerLookupResult {
	if o == nil || IsNil(o.CustomerLookup) {
		var ret DtoCustomerLookupResult
		return ret
	}
	return *o.CustomerLookup
}

// GetCustomerLookupOk returns a tuple with the CustomerLookup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDebugTracker) GetCustomerLookupOk() (*DtoCustomerLookupResult, bool) {
	if o == nil || IsNil(o.CustomerLookup) {
		return nil, false
	}
	return o.CustomerLookup, true
}

// HasCustomerLookup returns a boolean if a field has been set.
func (o *DtoDebugTracker) HasCustomerLookup() bool {
	if o != nil && !IsNil(o.CustomerLookup) {
		return true
	}

	return false
}

// SetCustomerLookup gets a reference to the given DtoCustomerLookupResult and assigns it to the CustomerLookup field.
func (o *DtoDebugTracker) SetCustomerLookup(v DtoCustomerLookupResult) {
	o.CustomerLookup = &v
}

// GetFailurePoint returns the FailurePoint field value if set, zero value otherwise.
func (o *DtoDebugTracker) GetFailurePoint() TypesFailurePoint {
	if o == nil || IsNil(o.FailurePoint) {
		var ret TypesFailurePoint
		return ret
	}
	return *o.FailurePoint
}

// GetFailurePointOk returns a tuple with the FailurePoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDebugTracker) GetFailurePointOk() (*TypesFailurePoint, bool) {
	if o == nil || IsNil(o.FailurePoint) {
		return nil, false
	}
	return o.FailurePoint, true
}

// HasFailurePoint returns a boolean if a field has been set.
func (o *DtoDebugTracker) HasFailurePoint() bool {
	if o != nil && !IsNil(o.FailurePoint) {
		return true
	}

	return false
}

// SetFailurePoint gets a reference to the given TypesFailurePoint and assigns it to the FailurePoint field.
func (o *DtoDebugTracker) SetFailurePoint(v TypesFailurePoint) {
	o.FailurePoint = &v
}

// GetMeterMatching returns the MeterMatching field value if set, zero value otherwise.
func (o *DtoDebugTracker) GetMeterMatching() DtoMeterMatchingResult {
	if o == nil || IsNil(o.MeterMatching) {
		var ret DtoMeterMatchingResult
		return ret
	}
	return *o.MeterMatching
}

// GetMeterMatchingOk returns a tuple with the MeterMatching field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDebugTracker) GetMeterMatchingOk() (*DtoMeterMatchingResult, bool) {
	if o == nil || IsNil(o.MeterMatching) {
		return nil, false
	}
	return o.MeterMatching, true
}

// HasMeterMatching returns a boolean if a field has been set.
func (o *DtoDebugTracker) HasMeterMatching() bool {
	if o != nil && !IsNil(o.MeterMatching) {
		return true
	}

	return false
}

// SetMeterMatching gets a reference to the given DtoMeterMatchingResult and assigns it to the MeterMatching field.
func (o *DtoDebugTracker) SetMeterMatching(v DtoMeterMatchingResult) {
	o.MeterMatching = &v
}

// GetPriceLookup returns the PriceLookup field value if set, zero value otherwise.
func (o *DtoDebugTracker) GetPriceLookup() DtoPriceLookupResult {
	if o == nil || IsNil(o.PriceLookup) {
		var ret DtoPriceLookupResult
		return ret
	}
	return *o.PriceLookup
}

// GetPriceLookupOk returns a tuple with the PriceLookup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDebugTracker) GetPriceLookupOk() (*DtoPriceLookupResult, bool) {
	if o == nil || IsNil(o.PriceLookup) {
		return nil, false
	}
	return o.PriceLookup, true
}

// HasPriceLookup returns a boolean if a field has been set.
func (o *DtoDebugTracker) HasPriceLookup() bool {
	if o != nil && !IsNil(o.PriceLookup) {
		return true
	}

	return false
}

// SetPriceLookup gets a reference to the given DtoPriceLookupResult and assigns it to the PriceLookup field.
func (o *DtoDebugTracker) SetPriceLookup(v DtoPriceLookupResult) {
	o.PriceLookup = &v
}

// GetSubscriptionLineItemLookup returns the SubscriptionLineItemLookup field value if set, zero value otherwise.
func (o *DtoDebugTracker) GetSubscriptionLineItemLookup() DtoSubscriptionLineItemLookupResult {
	if o == nil || IsNil(o.SubscriptionLineItemLookup) {
		var ret DtoSubscriptionLineItemLookupResult
		return ret
	}
	return *o.SubscriptionLineItemLookup
}

// GetSubscriptionLineItemLookupOk returns a tuple with the SubscriptionLineItemLookup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDebugTracker) GetSubscriptionLineItemLookupOk() (*DtoSubscriptionLineItemLookupResult, bool) {
	if o == nil || IsNil(o.SubscriptionLineItemLookup) {
		return nil, false
	}
	return o.SubscriptionLineItemLookup, true
}

// HasSubscriptionLineItemLookup returns a boolean if a field has been set.
func (o *DtoDebugTracker) HasSubscriptionLineItemLookup() bool {
	if o != nil && !IsNil(o.SubscriptionLineItemLookup) {
		return true
	}

	return false
}

// SetSubscriptionLineItemLookup gets a reference to the given DtoSubscriptionLineItemLookupResult and assigns it to the SubscriptionLineItemLookup field.
func (o *DtoDebugTracker) SetSubscriptionLineItemLookup(v DtoSubscriptionLineItemLookupResult) {
	o.SubscriptionLineItemLookup = &v
}

func (o DtoDebugTracker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoDebugTracker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerLookup) {
		toSerialize["customer_lookup"] = o.CustomerLookup
	}
	if !IsNil(o.FailurePoint) {
		toSerialize["failure_point"] = o.FailurePoint
	}
	if !IsNil(o.MeterMatching) {
		toSerialize["meter_matching"] = o.MeterMatching
	}
	if !IsNil(o.PriceLookup) {
		toSerialize["price_lookup"] = o.PriceLookup
	}
	if !IsNil(o.SubscriptionLineItemLookup) {
		toSerialize["subscription_line_item_lookup"] = o.SubscriptionLineItemLookup
	}
	return toSerialize, nil
}

type NullableDtoDebugTracker struct {
	value *DtoDebugTracker
	isSet bool
}

func (v NullableDtoDebugTracker) Get() *DtoDebugTracker {
	return v.value
}

func (v *NullableDtoDebugTracker) Set(val *DtoDebugTracker) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoDebugTracker) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoDebugTracker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoDebugTracker(val *DtoDebugTracker) *NullableDtoDebugTracker {
	return &NullableDtoDebugTracker{value: val, isSet: true}
}

func (v NullableDtoDebugTracker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoDebugTracker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


