/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoUpdateSubscriptionLineItemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateSubscriptionLineItemRequest{}

// DtoUpdateSubscriptionLineItemRequest struct for DtoUpdateSubscriptionLineItemRequest
type DtoUpdateSubscriptionLineItemRequest struct {
	// Amount is the new price amount that overrides the original price
	Amount *string `json:"amount,omitempty"`
	BillingModel *TypesBillingModel `json:"billing_model,omitempty"`
	// Commitment fields
	CommitmentAmount *float32 `json:"commitment_amount,omitempty"`
	CommitmentOverageFactor *float32 `json:"commitment_overage_factor,omitempty"`
	CommitmentQuantity *float32 `json:"commitment_quantity,omitempty"`
	CommitmentTrueUpEnabled *bool `json:"commitment_true_up_enabled,omitempty"`
	CommitmentType *TypesCommitmentType `json:"commitment_type,omitempty"`
	CommitmentWindowed *bool `json:"commitment_windowed,omitempty"`
	// EffectiveFrom for the existing line item (if not provided, defaults to now)
	EffectiveFrom *string `json:"effective_from,omitempty"`
	// Metadata for the new line item
	Metadata *map[string]string `json:"metadata,omitempty"`
	TierMode *TypesBillingTier `json:"tier_mode,omitempty"`
	// Tiers determines the pricing tiers for this line item
	Tiers []DtoCreatePriceTier `json:"tiers,omitempty"`
	TransformQuantity *PriceTransformQuantity `json:"transform_quantity,omitempty"`
}

// NewDtoUpdateSubscriptionLineItemRequest instantiates a new DtoUpdateSubscriptionLineItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateSubscriptionLineItemRequest() *DtoUpdateSubscriptionLineItemRequest {
	this := DtoUpdateSubscriptionLineItemRequest{}
	return &this
}

// NewDtoUpdateSubscriptionLineItemRequestWithDefaults instantiates a new DtoUpdateSubscriptionLineItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateSubscriptionLineItemRequestWithDefaults() *DtoUpdateSubscriptionLineItemRequest {
	this := DtoUpdateSubscriptionLineItemRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetAmount(v string) {
	o.Amount = &v
}

// GetBillingModel returns the BillingModel field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetBillingModel() TypesBillingModel {
	if o == nil || IsNil(o.BillingModel) {
		var ret TypesBillingModel
		return ret
	}
	return *o.BillingModel
}

// GetBillingModelOk returns a tuple with the BillingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetBillingModelOk() (*TypesBillingModel, bool) {
	if o == nil || IsNil(o.BillingModel) {
		return nil, false
	}
	return o.BillingModel, true
}

// HasBillingModel returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasBillingModel() bool {
	if o != nil && !IsNil(o.BillingModel) {
		return true
	}

	return false
}

// SetBillingModel gets a reference to the given TypesBillingModel and assigns it to the BillingModel field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetBillingModel(v TypesBillingModel) {
	o.BillingModel = &v
}

// GetCommitmentAmount returns the CommitmentAmount field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentAmount() float32 {
	if o == nil || IsNil(o.CommitmentAmount) {
		var ret float32
		return ret
	}
	return *o.CommitmentAmount
}

// GetCommitmentAmountOk returns a tuple with the CommitmentAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.CommitmentAmount) {
		return nil, false
	}
	return o.CommitmentAmount, true
}

// HasCommitmentAmount returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentAmount() bool {
	if o != nil && !IsNil(o.CommitmentAmount) {
		return true
	}

	return false
}

// SetCommitmentAmount gets a reference to the given float32 and assigns it to the CommitmentAmount field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentAmount(v float32) {
	o.CommitmentAmount = &v
}

// GetCommitmentOverageFactor returns the CommitmentOverageFactor field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentOverageFactor() float32 {
	if o == nil || IsNil(o.CommitmentOverageFactor) {
		var ret float32
		return ret
	}
	return *o.CommitmentOverageFactor
}

// GetCommitmentOverageFactorOk returns a tuple with the CommitmentOverageFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentOverageFactorOk() (*float32, bool) {
	if o == nil || IsNil(o.CommitmentOverageFactor) {
		return nil, false
	}
	return o.CommitmentOverageFactor, true
}

// HasCommitmentOverageFactor returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentOverageFactor() bool {
	if o != nil && !IsNil(o.CommitmentOverageFactor) {
		return true
	}

	return false
}

// SetCommitmentOverageFactor gets a reference to the given float32 and assigns it to the CommitmentOverageFactor field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentOverageFactor(v float32) {
	o.CommitmentOverageFactor = &v
}

// GetCommitmentQuantity returns the CommitmentQuantity field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentQuantity() float32 {
	if o == nil || IsNil(o.CommitmentQuantity) {
		var ret float32
		return ret
	}
	return *o.CommitmentQuantity
}

// GetCommitmentQuantityOk returns a tuple with the CommitmentQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.CommitmentQuantity) {
		return nil, false
	}
	return o.CommitmentQuantity, true
}

// HasCommitmentQuantity returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentQuantity() bool {
	if o != nil && !IsNil(o.CommitmentQuantity) {
		return true
	}

	return false
}

// SetCommitmentQuantity gets a reference to the given float32 and assigns it to the CommitmentQuantity field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentQuantity(v float32) {
	o.CommitmentQuantity = &v
}

// GetCommitmentTrueUpEnabled returns the CommitmentTrueUpEnabled field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentTrueUpEnabled() bool {
	if o == nil || IsNil(o.CommitmentTrueUpEnabled) {
		var ret bool
		return ret
	}
	return *o.CommitmentTrueUpEnabled
}

// GetCommitmentTrueUpEnabledOk returns a tuple with the CommitmentTrueUpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentTrueUpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.CommitmentTrueUpEnabled) {
		return nil, false
	}
	return o.CommitmentTrueUpEnabled, true
}

// HasCommitmentTrueUpEnabled returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentTrueUpEnabled() bool {
	if o != nil && !IsNil(o.CommitmentTrueUpEnabled) {
		return true
	}

	return false
}

// SetCommitmentTrueUpEnabled gets a reference to the given bool and assigns it to the CommitmentTrueUpEnabled field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentTrueUpEnabled(v bool) {
	o.CommitmentTrueUpEnabled = &v
}

// GetCommitmentType returns the CommitmentType field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentType() TypesCommitmentType {
	if o == nil || IsNil(o.CommitmentType) {
		var ret TypesCommitmentType
		return ret
	}
	return *o.CommitmentType
}

// GetCommitmentTypeOk returns a tuple with the CommitmentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentTypeOk() (*TypesCommitmentType, bool) {
	if o == nil || IsNil(o.CommitmentType) {
		return nil, false
	}
	return o.CommitmentType, true
}

// HasCommitmentType returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentType() bool {
	if o != nil && !IsNil(o.CommitmentType) {
		return true
	}

	return false
}

// SetCommitmentType gets a reference to the given TypesCommitmentType and assigns it to the CommitmentType field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentType(v TypesCommitmentType) {
	o.CommitmentType = &v
}

// GetCommitmentWindowed returns the CommitmentWindowed field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentWindowed() bool {
	if o == nil || IsNil(o.CommitmentWindowed) {
		var ret bool
		return ret
	}
	return *o.CommitmentWindowed
}

// GetCommitmentWindowedOk returns a tuple with the CommitmentWindowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetCommitmentWindowedOk() (*bool, bool) {
	if o == nil || IsNil(o.CommitmentWindowed) {
		return nil, false
	}
	return o.CommitmentWindowed, true
}

// HasCommitmentWindowed returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasCommitmentWindowed() bool {
	if o != nil && !IsNil(o.CommitmentWindowed) {
		return true
	}

	return false
}

// SetCommitmentWindowed gets a reference to the given bool and assigns it to the CommitmentWindowed field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetCommitmentWindowed(v bool) {
	o.CommitmentWindowed = &v
}

// GetEffectiveFrom returns the EffectiveFrom field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetEffectiveFrom() string {
	if o == nil || IsNil(o.EffectiveFrom) {
		var ret string
		return ret
	}
	return *o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetEffectiveFromOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveFrom) {
		return nil, false
	}
	return o.EffectiveFrom, true
}

// HasEffectiveFrom returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasEffectiveFrom() bool {
	if o != nil && !IsNil(o.EffectiveFrom) {
		return true
	}

	return false
}

// SetEffectiveFrom gets a reference to the given string and assigns it to the EffectiveFrom field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetEffectiveFrom(v string) {
	o.EffectiveFrom = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetTierMode returns the TierMode field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTierMode() TypesBillingTier {
	if o == nil || IsNil(o.TierMode) {
		var ret TypesBillingTier
		return ret
	}
	return *o.TierMode
}

// GetTierModeOk returns a tuple with the TierMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTierModeOk() (*TypesBillingTier, bool) {
	if o == nil || IsNil(o.TierMode) {
		return nil, false
	}
	return o.TierMode, true
}

// HasTierMode returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasTierMode() bool {
	if o != nil && !IsNil(o.TierMode) {
		return true
	}

	return false
}

// SetTierMode gets a reference to the given TypesBillingTier and assigns it to the TierMode field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetTierMode(v TypesBillingTier) {
	o.TierMode = &v
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTiers() []DtoCreatePriceTier {
	if o == nil || IsNil(o.Tiers) {
		var ret []DtoCreatePriceTier
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTiersOk() ([]DtoCreatePriceTier, bool) {
	if o == nil || IsNil(o.Tiers) {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasTiers() bool {
	if o != nil && !IsNil(o.Tiers) {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []DtoCreatePriceTier and assigns it to the Tiers field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetTiers(v []DtoCreatePriceTier) {
	o.Tiers = v
}

// GetTransformQuantity returns the TransformQuantity field value if set, zero value otherwise.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTransformQuantity() PriceTransformQuantity {
	if o == nil || IsNil(o.TransformQuantity) {
		var ret PriceTransformQuantity
		return ret
	}
	return *o.TransformQuantity
}

// GetTransformQuantityOk returns a tuple with the TransformQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) GetTransformQuantityOk() (*PriceTransformQuantity, bool) {
	if o == nil || IsNil(o.TransformQuantity) {
		return nil, false
	}
	return o.TransformQuantity, true
}

// HasTransformQuantity returns a boolean if a field has been set.
func (o *DtoUpdateSubscriptionLineItemRequest) HasTransformQuantity() bool {
	if o != nil && !IsNil(o.TransformQuantity) {
		return true
	}

	return false
}

// SetTransformQuantity gets a reference to the given PriceTransformQuantity and assigns it to the TransformQuantity field.
func (o *DtoUpdateSubscriptionLineItemRequest) SetTransformQuantity(v PriceTransformQuantity) {
	o.TransformQuantity = &v
}

func (o DtoUpdateSubscriptionLineItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateSubscriptionLineItemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.BillingModel) {
		toSerialize["billing_model"] = o.BillingModel
	}
	if !IsNil(o.CommitmentAmount) {
		toSerialize["commitment_amount"] = o.CommitmentAmount
	}
	if !IsNil(o.CommitmentOverageFactor) {
		toSerialize["commitment_overage_factor"] = o.CommitmentOverageFactor
	}
	if !IsNil(o.CommitmentQuantity) {
		toSerialize["commitment_quantity"] = o.CommitmentQuantity
	}
	if !IsNil(o.CommitmentTrueUpEnabled) {
		toSerialize["commitment_true_up_enabled"] = o.CommitmentTrueUpEnabled
	}
	if !IsNil(o.CommitmentType) {
		toSerialize["commitment_type"] = o.CommitmentType
	}
	if !IsNil(o.CommitmentWindowed) {
		toSerialize["commitment_windowed"] = o.CommitmentWindowed
	}
	if !IsNil(o.EffectiveFrom) {
		toSerialize["effective_from"] = o.EffectiveFrom
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.TierMode) {
		toSerialize["tier_mode"] = o.TierMode
	}
	if !IsNil(o.Tiers) {
		toSerialize["tiers"] = o.Tiers
	}
	if !IsNil(o.TransformQuantity) {
		toSerialize["transform_quantity"] = o.TransformQuantity
	}
	return toSerialize, nil
}

type NullableDtoUpdateSubscriptionLineItemRequest struct {
	value *DtoUpdateSubscriptionLineItemRequest
	isSet bool
}

func (v NullableDtoUpdateSubscriptionLineItemRequest) Get() *DtoUpdateSubscriptionLineItemRequest {
	return v.value
}

func (v *NullableDtoUpdateSubscriptionLineItemRequest) Set(val *DtoUpdateSubscriptionLineItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateSubscriptionLineItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateSubscriptionLineItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateSubscriptionLineItemRequest(val *DtoUpdateSubscriptionLineItemRequest) *NullableDtoUpdateSubscriptionLineItemRequest {
	return &NullableDtoUpdateSubscriptionLineItemRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateSubscriptionLineItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateSubscriptionLineItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


