/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the TypesConnectionSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesConnectionSettings{}

// TypesConnectionSettings struct for TypesConnectionSettings
type TypesConnectionSettings struct {
	InvoiceSyncEnable *bool `json:"invoice_sync_enable,omitempty"`
}

// NewTypesConnectionSettings instantiates a new TypesConnectionSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesConnectionSettings() *TypesConnectionSettings {
	this := TypesConnectionSettings{}
	return &this
}

// NewTypesConnectionSettingsWithDefaults instantiates a new TypesConnectionSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesConnectionSettingsWithDefaults() *TypesConnectionSettings {
	this := TypesConnectionSettings{}
	return &this
}

// GetInvoiceSyncEnable returns the InvoiceSyncEnable field value if set, zero value otherwise.
func (o *TypesConnectionSettings) GetInvoiceSyncEnable() bool {
	if o == nil || IsNil(o.InvoiceSyncEnable) {
		var ret bool
		return ret
	}
	return *o.InvoiceSyncEnable
}

// GetInvoiceSyncEnableOk returns a tuple with the InvoiceSyncEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesConnectionSettings) GetInvoiceSyncEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.InvoiceSyncEnable) {
		return nil, false
	}
	return o.InvoiceSyncEnable, true
}

// HasInvoiceSyncEnable returns a boolean if a field has been set.
func (o *TypesConnectionSettings) HasInvoiceSyncEnable() bool {
	if o != nil && !IsNil(o.InvoiceSyncEnable) {
		return true
	}

	return false
}

// SetInvoiceSyncEnable gets a reference to the given bool and assigns it to the InvoiceSyncEnable field.
func (o *TypesConnectionSettings) SetInvoiceSyncEnable(v bool) {
	o.InvoiceSyncEnable = &v
}

func (o TypesConnectionSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesConnectionSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InvoiceSyncEnable) {
		toSerialize["invoice_sync_enable"] = o.InvoiceSyncEnable
	}
	return toSerialize, nil
}

type NullableTypesConnectionSettings struct {
	value *TypesConnectionSettings
	isSet bool
}

func (v NullableTypesConnectionSettings) Get() *TypesConnectionSettings {
	return v.value
}

func (v *NullableTypesConnectionSettings) Set(val *TypesConnectionSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesConnectionSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesConnectionSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesConnectionSettings(val *TypesConnectionSettings) *NullableTypesConnectionSettings {
	return &NullableTypesConnectionSettings{value: val, isSet: true}
}

func (v NullableTypesConnectionSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesConnectionSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


