/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoSuccessResponse{}

// DtoSuccessResponse struct for DtoSuccessResponse
type DtoSuccessResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewDtoSuccessResponse instantiates a new DtoSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoSuccessResponse() *DtoSuccessResponse {
	this := DtoSuccessResponse{}
	return &this
}

// NewDtoSuccessResponseWithDefaults instantiates a new DtoSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoSuccessResponseWithDefaults() *DtoSuccessResponse {
	this := DtoSuccessResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoSuccessResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSuccessResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoSuccessResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoSuccessResponse) SetMessage(v string) {
	o.Message = &v
}

func (o DtoSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDtoSuccessResponse struct {
	value *DtoSuccessResponse
	isSet bool
}

func (v NullableDtoSuccessResponse) Get() *DtoSuccessResponse {
	return v.value
}

func (v *NullableDtoSuccessResponse) Set(val *DtoSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoSuccessResponse(val *DtoSuccessResponse) *NullableDtoSuccessResponse {
	return &NullableDtoSuccessResponse{value: val, isSet: true}
}

func (v NullableDtoSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


