/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the TypesEntitlementFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesEntitlementFilter{}

// TypesEntitlementFilter struct for TypesEntitlementFilter
type TypesEntitlementFilter struct {
	EndTime *string `json:"end_time,omitempty"`
	EntityIds []string `json:"entity_ids,omitempty"`
	EntityType *TypesEntitlementEntityType `json:"entity_type,omitempty"`
	Expand *string `json:"expand,omitempty"`
	FeatureIds []string `json:"feature_ids,omitempty"`
	FeatureType *TypesFeatureType `json:"feature_type,omitempty"`
	// Specific filters for entitlements
	Filters []TypesFilterCondition `json:"filters,omitempty"`
	IsEnabled *bool `json:"is_enabled,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Order *string `json:"order,omitempty"`
	PlanIds []string `json:"plan_ids,omitempty"`
	Sort []TypesSortCondition `json:"sort,omitempty"`
	StartTime *string `json:"start_time,omitempty"`
	Status *TypesStatus `json:"status,omitempty"`
}

// NewTypesEntitlementFilter instantiates a new TypesEntitlementFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesEntitlementFilter() *TypesEntitlementFilter {
	this := TypesEntitlementFilter{}
	return &this
}

// NewTypesEntitlementFilterWithDefaults instantiates a new TypesEntitlementFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesEntitlementFilterWithDefaults() *TypesEntitlementFilter {
	this := TypesEntitlementFilter{}
	return &this
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetEndTime() string {
	if o == nil || IsNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *TypesEntitlementFilter) SetEndTime(v string) {
	o.EndTime = &v
}

// GetEntityIds returns the EntityIds field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetEntityIds() []string {
	if o == nil || IsNil(o.EntityIds) {
		var ret []string
		return ret
	}
	return o.EntityIds
}

// GetEntityIdsOk returns a tuple with the EntityIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetEntityIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.EntityIds) {
		return nil, false
	}
	return o.EntityIds, true
}

// HasEntityIds returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasEntityIds() bool {
	if o != nil && !IsNil(o.EntityIds) {
		return true
	}

	return false
}

// SetEntityIds gets a reference to the given []string and assigns it to the EntityIds field.
func (o *TypesEntitlementFilter) SetEntityIds(v []string) {
	o.EntityIds = v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetEntityType() TypesEntitlementEntityType {
	if o == nil || IsNil(o.EntityType) {
		var ret TypesEntitlementEntityType
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetEntityTypeOk() (*TypesEntitlementEntityType, bool) {
	if o == nil || IsNil(o.EntityType) {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasEntityType() bool {
	if o != nil && !IsNil(o.EntityType) {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given TypesEntitlementEntityType and assigns it to the EntityType field.
func (o *TypesEntitlementFilter) SetEntityType(v TypesEntitlementEntityType) {
	o.EntityType = &v
}

// GetExpand returns the Expand field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetExpand() string {
	if o == nil || IsNil(o.Expand) {
		var ret string
		return ret
	}
	return *o.Expand
}

// GetExpandOk returns a tuple with the Expand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetExpandOk() (*string, bool) {
	if o == nil || IsNil(o.Expand) {
		return nil, false
	}
	return o.Expand, true
}

// HasExpand returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasExpand() bool {
	if o != nil && !IsNil(o.Expand) {
		return true
	}

	return false
}

// SetExpand gets a reference to the given string and assigns it to the Expand field.
func (o *TypesEntitlementFilter) SetExpand(v string) {
	o.Expand = &v
}

// GetFeatureIds returns the FeatureIds field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetFeatureIds() []string {
	if o == nil || IsNil(o.FeatureIds) {
		var ret []string
		return ret
	}
	return o.FeatureIds
}

// GetFeatureIdsOk returns a tuple with the FeatureIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetFeatureIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.FeatureIds) {
		return nil, false
	}
	return o.FeatureIds, true
}

// HasFeatureIds returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasFeatureIds() bool {
	if o != nil && !IsNil(o.FeatureIds) {
		return true
	}

	return false
}

// SetFeatureIds gets a reference to the given []string and assigns it to the FeatureIds field.
func (o *TypesEntitlementFilter) SetFeatureIds(v []string) {
	o.FeatureIds = v
}

// GetFeatureType returns the FeatureType field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetFeatureType() TypesFeatureType {
	if o == nil || IsNil(o.FeatureType) {
		var ret TypesFeatureType
		return ret
	}
	return *o.FeatureType
}

// GetFeatureTypeOk returns a tuple with the FeatureType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetFeatureTypeOk() (*TypesFeatureType, bool) {
	if o == nil || IsNil(o.FeatureType) {
		return nil, false
	}
	return o.FeatureType, true
}

// HasFeatureType returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasFeatureType() bool {
	if o != nil && !IsNil(o.FeatureType) {
		return true
	}

	return false
}

// SetFeatureType gets a reference to the given TypesFeatureType and assigns it to the FeatureType field.
func (o *TypesEntitlementFilter) SetFeatureType(v TypesFeatureType) {
	o.FeatureType = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetFilters() []TypesFilterCondition {
	if o == nil || IsNil(o.Filters) {
		var ret []TypesFilterCondition
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetFiltersOk() ([]TypesFilterCondition, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []TypesFilterCondition and assigns it to the Filters field.
func (o *TypesEntitlementFilter) SetFilters(v []TypesFilterCondition) {
	o.Filters = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *TypesEntitlementFilter) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *TypesEntitlementFilter) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *TypesEntitlementFilter) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *TypesEntitlementFilter) SetOrder(v string) {
	o.Order = &v
}

// GetPlanIds returns the PlanIds field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetPlanIds() []string {
	if o == nil || IsNil(o.PlanIds) {
		var ret []string
		return ret
	}
	return o.PlanIds
}

// GetPlanIdsOk returns a tuple with the PlanIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetPlanIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PlanIds) {
		return nil, false
	}
	return o.PlanIds, true
}

// HasPlanIds returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasPlanIds() bool {
	if o != nil && !IsNil(o.PlanIds) {
		return true
	}

	return false
}

// SetPlanIds gets a reference to the given []string and assigns it to the PlanIds field.
func (o *TypesEntitlementFilter) SetPlanIds(v []string) {
	o.PlanIds = v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetSort() []TypesSortCondition {
	if o == nil || IsNil(o.Sort) {
		var ret []TypesSortCondition
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetSortOk() ([]TypesSortCondition, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []TypesSortCondition and assigns it to the Sort field.
func (o *TypesEntitlementFilter) SetSort(v []TypesSortCondition) {
	o.Sort = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *TypesEntitlementFilter) SetStartTime(v string) {
	o.StartTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TypesEntitlementFilter) GetStatus() TypesStatus {
	if o == nil || IsNil(o.Status) {
		var ret TypesStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesEntitlementFilter) GetStatusOk() (*TypesStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TypesEntitlementFilter) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TypesStatus and assigns it to the Status field.
func (o *TypesEntitlementFilter) SetStatus(v TypesStatus) {
	o.Status = &v
}

func (o TypesEntitlementFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesEntitlementFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !IsNil(o.EntityIds) {
		toSerialize["entity_ids"] = o.EntityIds
	}
	if !IsNil(o.EntityType) {
		toSerialize["entity_type"] = o.EntityType
	}
	if !IsNil(o.Expand) {
		toSerialize["expand"] = o.Expand
	}
	if !IsNil(o.FeatureIds) {
		toSerialize["feature_ids"] = o.FeatureIds
	}
	if !IsNil(o.FeatureType) {
		toSerialize["feature_type"] = o.FeatureType
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.PlanIds) {
		toSerialize["plan_ids"] = o.PlanIds
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableTypesEntitlementFilter struct {
	value *TypesEntitlementFilter
	isSet bool
}

func (v NullableTypesEntitlementFilter) Get() *TypesEntitlementFilter {
	return v.value
}

func (v *NullableTypesEntitlementFilter) Set(val *TypesEntitlementFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesEntitlementFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesEntitlementFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesEntitlementFilter(val *TypesEntitlementFilter) *NullableTypesEntitlementFilter {
	return &NullableTypesEntitlementFilter{value: val, isSet: true}
}

func (v NullableTypesEntitlementFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesEntitlementFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


