/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"fmt"
)

// TypesEventProcessingStatusType the model 'TypesEventProcessingStatusType'
type TypesEventProcessingStatusType string

// List of types.EventProcessingStatusType
const (
	TYPESEVENTPROCESSINGSTATUSTYPE_EventProcessingStatusTypeProcessed TypesEventProcessingStatusType = "processed"
	TYPESEVENTPROCESSINGSTATUSTYPE_EventProcessingStatusTypeProcessing TypesEventProcessingStatusType = "processing"
	TYPESEVENTPROCESSINGSTATUSTYPE_EventProcessingStatusTypeFailed TypesEventProcessingStatusType = "failed"
)

// All allowed values of TypesEventProcessingStatusType enum
var AllowedTypesEventProcessingStatusTypeEnumValues = []TypesEventProcessingStatusType{
	"processed",
	"processing",
	"failed",
}

func (v *TypesEventProcessingStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesEventProcessingStatusType(value)
	for _, existing := range AllowedTypesEventProcessingStatusTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesEventProcessingStatusType", value)
}

// NewTypesEventProcessingStatusTypeFromValue returns a pointer to a valid TypesEventProcessingStatusType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesEventProcessingStatusTypeFromValue(v string) (*TypesEventProcessingStatusType, error) {
	ev := TypesEventProcessingStatusType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesEventProcessingStatusType: valid values are %v", v, AllowedTypesEventProcessingStatusTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesEventProcessingStatusType) IsValid() bool {
	for _, existing := range AllowedTypesEventProcessingStatusTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.EventProcessingStatusType value
func (v TypesEventProcessingStatusType) Ptr() *TypesEventProcessingStatusType {
	return &v
}

type NullableTypesEventProcessingStatusType struct {
	value *TypesEventProcessingStatusType
	isSet bool
}

func (v NullableTypesEventProcessingStatusType) Get() *TypesEventProcessingStatusType {
	return v.value
}

func (v *NullableTypesEventProcessingStatusType) Set(val *TypesEventProcessingStatusType) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesEventProcessingStatusType) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesEventProcessingStatusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesEventProcessingStatusType(val *TypesEventProcessingStatusType) *NullableTypesEventProcessingStatusType {
	return &NullableTypesEventProcessingStatusType{value: val, isSet: true}
}

func (v NullableTypesEventProcessingStatusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesEventProcessingStatusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

