/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoCreateBulkEntitlementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateBulkEntitlementResponse{}

// DtoCreateBulkEntitlementResponse struct for DtoCreateBulkEntitlementResponse
type DtoCreateBulkEntitlementResponse struct {
	Items []DtoEntitlementResponse `json:"items,omitempty"`
}

// NewDtoCreateBulkEntitlementResponse instantiates a new DtoCreateBulkEntitlementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateBulkEntitlementResponse() *DtoCreateBulkEntitlementResponse {
	this := DtoCreateBulkEntitlementResponse{}
	return &this
}

// NewDtoCreateBulkEntitlementResponseWithDefaults instantiates a new DtoCreateBulkEntitlementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateBulkEntitlementResponseWithDefaults() *DtoCreateBulkEntitlementResponse {
	this := DtoCreateBulkEntitlementResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoCreateBulkEntitlementResponse) GetItems() []DtoEntitlementResponse {
	if o == nil || IsNil(o.Items) {
		var ret []DtoEntitlementResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateBulkEntitlementResponse) GetItemsOk() ([]DtoEntitlementResponse, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoCreateBulkEntitlementResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DtoEntitlementResponse and assigns it to the Items field.
func (o *DtoCreateBulkEntitlementResponse) SetItems(v []DtoEntitlementResponse) {
	o.Items = v
}

func (o DtoCreateBulkEntitlementResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateBulkEntitlementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableDtoCreateBulkEntitlementResponse struct {
	value *DtoCreateBulkEntitlementResponse
	isSet bool
}

func (v NullableDtoCreateBulkEntitlementResponse) Get() *DtoCreateBulkEntitlementResponse {
	return v.value
}

func (v *NullableDtoCreateBulkEntitlementResponse) Set(val *DtoCreateBulkEntitlementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateBulkEntitlementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateBulkEntitlementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateBulkEntitlementResponse(val *DtoCreateBulkEntitlementResponse) *NullableDtoCreateBulkEntitlementResponse {
	return &NullableDtoCreateBulkEntitlementResponse{value: val, isSet: true}
}

func (v NullableDtoCreateBulkEntitlementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateBulkEntitlementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


