/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoTopUpWalletResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoTopUpWalletResponse{}

// DtoTopUpWalletResponse struct for DtoTopUpWalletResponse
type DtoTopUpWalletResponse struct {
	// Invoice ID if an invoice was created (only for PURCHASED_CREDIT_INVOICED)
	InvoiceId *string `json:"invoice_id,omitempty"`
	Wallet *DtoWalletResponse `json:"wallet,omitempty"`
	WalletTransaction *DtoWalletTransactionResponse `json:"wallet_transaction,omitempty"`
}

// NewDtoTopUpWalletResponse instantiates a new DtoTopUpWalletResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoTopUpWalletResponse() *DtoTopUpWalletResponse {
	this := DtoTopUpWalletResponse{}
	return &this
}

// NewDtoTopUpWalletResponseWithDefaults instantiates a new DtoTopUpWalletResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoTopUpWalletResponseWithDefaults() *DtoTopUpWalletResponse {
	this := DtoTopUpWalletResponse{}
	return &this
}

// GetInvoiceId returns the InvoiceId field value if set, zero value otherwise.
func (o *DtoTopUpWalletResponse) GetInvoiceId() string {
	if o == nil || IsNil(o.InvoiceId) {
		var ret string
		return ret
	}
	return *o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTopUpWalletResponse) GetInvoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceId) {
		return nil, false
	}
	return o.InvoiceId, true
}

// HasInvoiceId returns a boolean if a field has been set.
func (o *DtoTopUpWalletResponse) HasInvoiceId() bool {
	if o != nil && !IsNil(o.InvoiceId) {
		return true
	}

	return false
}

// SetInvoiceId gets a reference to the given string and assigns it to the InvoiceId field.
func (o *DtoTopUpWalletResponse) SetInvoiceId(v string) {
	o.InvoiceId = &v
}

// GetWallet returns the Wallet field value if set, zero value otherwise.
func (o *DtoTopUpWalletResponse) GetWallet() DtoWalletResponse {
	if o == nil || IsNil(o.Wallet) {
		var ret DtoWalletResponse
		return ret
	}
	return *o.Wallet
}

// GetWalletOk returns a tuple with the Wallet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTopUpWalletResponse) GetWalletOk() (*DtoWalletResponse, bool) {
	if o == nil || IsNil(o.Wallet) {
		return nil, false
	}
	return o.Wallet, true
}

// HasWallet returns a boolean if a field has been set.
func (o *DtoTopUpWalletResponse) HasWallet() bool {
	if o != nil && !IsNil(o.Wallet) {
		return true
	}

	return false
}

// SetWallet gets a reference to the given DtoWalletResponse and assigns it to the Wallet field.
func (o *DtoTopUpWalletResponse) SetWallet(v DtoWalletResponse) {
	o.Wallet = &v
}

// GetWalletTransaction returns the WalletTransaction field value if set, zero value otherwise.
func (o *DtoTopUpWalletResponse) GetWalletTransaction() DtoWalletTransactionResponse {
	if o == nil || IsNil(o.WalletTransaction) {
		var ret DtoWalletTransactionResponse
		return ret
	}
	return *o.WalletTransaction
}

// GetWalletTransactionOk returns a tuple with the WalletTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTopUpWalletResponse) GetWalletTransactionOk() (*DtoWalletTransactionResponse, bool) {
	if o == nil || IsNil(o.WalletTransaction) {
		return nil, false
	}
	return o.WalletTransaction, true
}

// HasWalletTransaction returns a boolean if a field has been set.
func (o *DtoTopUpWalletResponse) HasWalletTransaction() bool {
	if o != nil && !IsNil(o.WalletTransaction) {
		return true
	}

	return false
}

// SetWalletTransaction gets a reference to the given DtoWalletTransactionResponse and assigns it to the WalletTransaction field.
func (o *DtoTopUpWalletResponse) SetWalletTransaction(v DtoWalletTransactionResponse) {
	o.WalletTransaction = &v
}

func (o DtoTopUpWalletResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoTopUpWalletResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InvoiceId) {
		toSerialize["invoice_id"] = o.InvoiceId
	}
	if !IsNil(o.Wallet) {
		toSerialize["wallet"] = o.Wallet
	}
	if !IsNil(o.WalletTransaction) {
		toSerialize["wallet_transaction"] = o.WalletTransaction
	}
	return toSerialize, nil
}

type NullableDtoTopUpWalletResponse struct {
	value *DtoTopUpWalletResponse
	isSet bool
}

func (v NullableDtoTopUpWalletResponse) Get() *DtoTopUpWalletResponse {
	return v.value
}

func (v *NullableDtoTopUpWalletResponse) Set(val *DtoTopUpWalletResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoTopUpWalletResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoTopUpWalletResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoTopUpWalletResponse(val *DtoTopUpWalletResponse) *NullableDtoTopUpWalletResponse {
	return &NullableDtoTopUpWalletResponse{value: val, isSet: true}
}

func (v NullableDtoTopUpWalletResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoTopUpWalletResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


