/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoGetEventByIDResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoGetEventByIDResponse{}

// DtoGetEventByIDResponse struct for DtoGetEventByIDResponse
type DtoGetEventByIDResponse struct {
	DebugTracker *DtoDebugTracker `json:"debug_tracker,omitempty"`
	Event *DtoEvent `json:"event,omitempty"`
	ProcessedEvents []DtoFeatureUsageInfo `json:"processed_events,omitempty"`
	Status *TypesEventProcessingStatusType `json:"status,omitempty"`
}

// NewDtoGetEventByIDResponse instantiates a new DtoGetEventByIDResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoGetEventByIDResponse() *DtoGetEventByIDResponse {
	this := DtoGetEventByIDResponse{}
	return &this
}

// NewDtoGetEventByIDResponseWithDefaults instantiates a new DtoGetEventByIDResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoGetEventByIDResponseWithDefaults() *DtoGetEventByIDResponse {
	this := DtoGetEventByIDResponse{}
	return &this
}

// GetDebugTracker returns the DebugTracker field value if set, zero value otherwise.
func (o *DtoGetEventByIDResponse) GetDebugTracker() DtoDebugTracker {
	if o == nil || IsNil(o.DebugTracker) {
		var ret DtoDebugTracker
		return ret
	}
	return *o.DebugTracker
}

// GetDebugTrackerOk returns a tuple with the DebugTracker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGetEventByIDResponse) GetDebugTrackerOk() (*DtoDebugTracker, bool) {
	if o == nil || IsNil(o.DebugTracker) {
		return nil, false
	}
	return o.DebugTracker, true
}

// HasDebugTracker returns a boolean if a field has been set.
func (o *DtoGetEventByIDResponse) HasDebugTracker() bool {
	if o != nil && !IsNil(o.DebugTracker) {
		return true
	}

	return false
}

// SetDebugTracker gets a reference to the given DtoDebugTracker and assigns it to the DebugTracker field.
func (o *DtoGetEventByIDResponse) SetDebugTracker(v DtoDebugTracker) {
	o.DebugTracker = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *DtoGetEventByIDResponse) GetEvent() DtoEvent {
	if o == nil || IsNil(o.Event) {
		var ret DtoEvent
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGetEventByIDResponse) GetEventOk() (*DtoEvent, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *DtoGetEventByIDResponse) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given DtoEvent and assigns it to the Event field.
func (o *DtoGetEventByIDResponse) SetEvent(v DtoEvent) {
	o.Event = &v
}

// GetProcessedEvents returns the ProcessedEvents field value if set, zero value otherwise.
func (o *DtoGetEventByIDResponse) GetProcessedEvents() []DtoFeatureUsageInfo {
	if o == nil || IsNil(o.ProcessedEvents) {
		var ret []DtoFeatureUsageInfo
		return ret
	}
	return o.ProcessedEvents
}

// GetProcessedEventsOk returns a tuple with the ProcessedEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGetEventByIDResponse) GetProcessedEventsOk() ([]DtoFeatureUsageInfo, bool) {
	if o == nil || IsNil(o.ProcessedEvents) {
		return nil, false
	}
	return o.ProcessedEvents, true
}

// HasProcessedEvents returns a boolean if a field has been set.
func (o *DtoGetEventByIDResponse) HasProcessedEvents() bool {
	if o != nil && !IsNil(o.ProcessedEvents) {
		return true
	}

	return false
}

// SetProcessedEvents gets a reference to the given []DtoFeatureUsageInfo and assigns it to the ProcessedEvents field.
func (o *DtoGetEventByIDResponse) SetProcessedEvents(v []DtoFeatureUsageInfo) {
	o.ProcessedEvents = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DtoGetEventByIDResponse) GetStatus() TypesEventProcessingStatusType {
	if o == nil || IsNil(o.Status) {
		var ret TypesEventProcessingStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGetEventByIDResponse) GetStatusOk() (*TypesEventProcessingStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DtoGetEventByIDResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TypesEventProcessingStatusType and assigns it to the Status field.
func (o *DtoGetEventByIDResponse) SetStatus(v TypesEventProcessingStatusType) {
	o.Status = &v
}

func (o DtoGetEventByIDResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoGetEventByIDResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DebugTracker) {
		toSerialize["debug_tracker"] = o.DebugTracker
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.ProcessedEvents) {
		toSerialize["processed_events"] = o.ProcessedEvents
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableDtoGetEventByIDResponse struct {
	value *DtoGetEventByIDResponse
	isSet bool
}

func (v NullableDtoGetEventByIDResponse) Get() *DtoGetEventByIDResponse {
	return v.value
}

func (v *NullableDtoGetEventByIDResponse) Set(val *DtoGetEventByIDResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoGetEventByIDResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoGetEventByIDResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoGetEventByIDResponse(val *DtoGetEventByIDResponse) *NullableDtoGetEventByIDResponse {
	return &NullableDtoGetEventByIDResponse{value: val, isSet: true}
}

func (v NullableDtoGetEventByIDResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoGetEventByIDResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


