/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoDeleteCostsheetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoDeleteCostsheetResponse{}

// DtoDeleteCostsheetResponse struct for DtoDeleteCostsheetResponse
type DtoDeleteCostsheetResponse struct {
	Id *string `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewDtoDeleteCostsheetResponse instantiates a new DtoDeleteCostsheetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoDeleteCostsheetResponse() *DtoDeleteCostsheetResponse {
	this := DtoDeleteCostsheetResponse{}
	return &this
}

// NewDtoDeleteCostsheetResponseWithDefaults instantiates a new DtoDeleteCostsheetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoDeleteCostsheetResponseWithDefaults() *DtoDeleteCostsheetResponse {
	this := DtoDeleteCostsheetResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoDeleteCostsheetResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDeleteCostsheetResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoDeleteCostsheetResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoDeleteCostsheetResponse) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoDeleteCostsheetResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDeleteCostsheetResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoDeleteCostsheetResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoDeleteCostsheetResponse) SetMessage(v string) {
	o.Message = &v
}

func (o DtoDeleteCostsheetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoDeleteCostsheetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDtoDeleteCostsheetResponse struct {
	value *DtoDeleteCostsheetResponse
	isSet bool
}

func (v NullableDtoDeleteCostsheetResponse) Get() *DtoDeleteCostsheetResponse {
	return v.value
}

func (v *NullableDtoDeleteCostsheetResponse) Set(val *DtoDeleteCostsheetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoDeleteCostsheetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoDeleteCostsheetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoDeleteCostsheetResponse(val *DtoDeleteCostsheetResponse) *NullableDtoDeleteCostsheetResponse {
	return &NullableDtoDeleteCostsheetResponse{value: val, isSet: true}
}

func (v NullableDtoDeleteCostsheetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoDeleteCostsheetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


