/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoInvoicePreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoInvoicePreview{}

// DtoInvoicePreview struct for DtoInvoicePreview
type DtoInvoicePreview struct {
	// currency is the currency for all amounts
	Currency *string `json:"currency,omitempty"`
	// due_date is when the invoice would be due
	DueDate *string `json:"due_date,omitempty"`
	// line_items contains preview of line items
	LineItems []DtoInvoiceLineItemPreview `json:"line_items,omitempty"`
	// subtotal is the subtotal amount before taxes
	Subtotal *string `json:"subtotal,omitempty"`
	// tax_amount is the total tax amount
	TaxAmount *string `json:"tax_amount,omitempty"`
	// total is the total amount including taxes
	Total *string `json:"total,omitempty"`
}

// NewDtoInvoicePreview instantiates a new DtoInvoicePreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoInvoicePreview() *DtoInvoicePreview {
	this := DtoInvoicePreview{}
	return &this
}

// NewDtoInvoicePreviewWithDefaults instantiates a new DtoInvoicePreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoInvoicePreviewWithDefaults() *DtoInvoicePreview {
	this := DtoInvoicePreview{}
	return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DtoInvoicePreview) SetCurrency(v string) {
	o.Currency = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *DtoInvoicePreview) SetDueDate(v string) {
	o.DueDate = &v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetLineItems() []DtoInvoiceLineItemPreview {
	if o == nil || IsNil(o.LineItems) {
		var ret []DtoInvoiceLineItemPreview
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetLineItemsOk() ([]DtoInvoiceLineItemPreview, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []DtoInvoiceLineItemPreview and assigns it to the LineItems field.
func (o *DtoInvoicePreview) SetLineItems(v []DtoInvoiceLineItemPreview) {
	o.LineItems = v
}

// GetSubtotal returns the Subtotal field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetSubtotal() string {
	if o == nil || IsNil(o.Subtotal) {
		var ret string
		return ret
	}
	return *o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetSubtotalOk() (*string, bool) {
	if o == nil || IsNil(o.Subtotal) {
		return nil, false
	}
	return o.Subtotal, true
}

// HasSubtotal returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasSubtotal() bool {
	if o != nil && !IsNil(o.Subtotal) {
		return true
	}

	return false
}

// SetSubtotal gets a reference to the given string and assigns it to the Subtotal field.
func (o *DtoInvoicePreview) SetSubtotal(v string) {
	o.Subtotal = &v
}

// GetTaxAmount returns the TaxAmount field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetTaxAmount() string {
	if o == nil || IsNil(o.TaxAmount) {
		var ret string
		return ret
	}
	return *o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetTaxAmountOk() (*string, bool) {
	if o == nil || IsNil(o.TaxAmount) {
		return nil, false
	}
	return o.TaxAmount, true
}

// HasTaxAmount returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasTaxAmount() bool {
	if o != nil && !IsNil(o.TaxAmount) {
		return true
	}

	return false
}

// SetTaxAmount gets a reference to the given string and assigns it to the TaxAmount field.
func (o *DtoInvoicePreview) SetTaxAmount(v string) {
	o.TaxAmount = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *DtoInvoicePreview) GetTotal() string {
	if o == nil || IsNil(o.Total) {
		var ret string
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoicePreview) GetTotalOk() (*string, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *DtoInvoicePreview) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given string and assigns it to the Total field.
func (o *DtoInvoicePreview) SetTotal(v string) {
	o.Total = &v
}

func (o DtoInvoicePreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoInvoicePreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.DueDate) {
		toSerialize["due_date"] = o.DueDate
	}
	if !IsNil(o.LineItems) {
		toSerialize["line_items"] = o.LineItems
	}
	if !IsNil(o.Subtotal) {
		toSerialize["subtotal"] = o.Subtotal
	}
	if !IsNil(o.TaxAmount) {
		toSerialize["tax_amount"] = o.TaxAmount
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableDtoInvoicePreview struct {
	value *DtoInvoicePreview
	isSet bool
}

func (v NullableDtoInvoicePreview) Get() *DtoInvoicePreview {
	return v.value
}

func (v *NullableDtoInvoicePreview) Set(val *DtoInvoicePreview) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoInvoicePreview) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoInvoicePreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoInvoicePreview(val *DtoInvoicePreview) *NullableDtoInvoicePreview {
	return &NullableDtoInvoicePreview{value: val, isSet: true}
}

func (v NullableDtoInvoicePreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoInvoicePreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


