/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"fmt"
)

// TypesCreditGrantExpiryType the model 'TypesCreditGrantExpiryType'
type TypesCreditGrantExpiryType string

// List of types.CreditGrantExpiryType
const (
	TYPESCREDITGRANTEXPIRYTYPE_CreditGrantExpiryTypeNever TypesCreditGrantExpiryType = "NEVER"
	TYPESCREDITGRANTEXPIRYTYPE_CreditGrantExpiryTypeDuration TypesCreditGrantExpiryType = "DURATION"
	TYPESCREDITGRANTEXPIRYTYPE_CreditGrantExpiryTypeBillingCycle TypesCreditGrantExpiryType = "BILLING_CYCLE"
)

// All allowed values of TypesCreditGrantExpiryType enum
var AllowedTypesCreditGrantExpiryTypeEnumValues = []TypesCreditGrantExpiryType{
	"NEVER",
	"DURATION",
	"BILLING_CYCLE",
}

func (v *TypesCreditGrantExpiryType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesCreditGrantExpiryType(value)
	for _, existing := range AllowedTypesCreditGrantExpiryTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesCreditGrantExpiryType", value)
}

// NewTypesCreditGrantExpiryTypeFromValue returns a pointer to a valid TypesCreditGrantExpiryType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesCreditGrantExpiryTypeFromValue(v string) (*TypesCreditGrantExpiryType, error) {
	ev := TypesCreditGrantExpiryType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesCreditGrantExpiryType: valid values are %v", v, AllowedTypesCreditGrantExpiryTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesCreditGrantExpiryType) IsValid() bool {
	for _, existing := range AllowedTypesCreditGrantExpiryTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.CreditGrantExpiryType value
func (v TypesCreditGrantExpiryType) Ptr() *TypesCreditGrantExpiryType {
	return &v
}

type NullableTypesCreditGrantExpiryType struct {
	value *TypesCreditGrantExpiryType
	isSet bool
}

func (v NullableTypesCreditGrantExpiryType) Get() *TypesCreditGrantExpiryType {
	return v.value
}

func (v *NullableTypesCreditGrantExpiryType) Set(val *TypesCreditGrantExpiryType) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesCreditGrantExpiryType) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesCreditGrantExpiryType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesCreditGrantExpiryType(val *TypesCreditGrantExpiryType) *NullableTypesCreditGrantExpiryType {
	return &NullableTypesCreditGrantExpiryType{value: val, isSet: true}
}

func (v NullableTypesCreditGrantExpiryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesCreditGrantExpiryType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

