/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"fmt"
)

// TypesPriceEntityType the model 'TypesPriceEntityType'
type TypesPriceEntityType string

// List of types.PriceEntityType
const (
	TYPESPRICEENTITYTYPE_PRICE_ENTITY_TYPE_PLAN TypesPriceEntityType = "PLAN"
	TYPESPRICEENTITYTYPE_PRICE_ENTITY_TYPE_SUBSCRIPTION TypesPriceEntityType = "SUBSCRIPTION"
	TYPESPRICEENTITYTYPE_PRICE_ENTITY_TYPE_ADDON TypesPriceEntityType = "ADDON"
	TYPESPRICEENTITYTYPE_PRICE_ENTITY_TYPE_PRICE TypesPriceEntityType = "PRICE"
	TYPESPRICEENTITYTYPE_PRICE_ENTITY_TYPE_COSTSHEET TypesPriceEntityType = "COSTSHEET"
)

// All allowed values of TypesPriceEntityType enum
var AllowedTypesPriceEntityTypeEnumValues = []TypesPriceEntityType{
	"PLAN",
	"SUBSCRIPTION",
	"ADDON",
	"PRICE",
	"COSTSHEET",
}

func (v *TypesPriceEntityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesPriceEntityType(value)
	for _, existing := range AllowedTypesPriceEntityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesPriceEntityType", value)
}

// NewTypesPriceEntityTypeFromValue returns a pointer to a valid TypesPriceEntityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesPriceEntityTypeFromValue(v string) (*TypesPriceEntityType, error) {
	ev := TypesPriceEntityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesPriceEntityType: valid values are %v", v, AllowedTypesPriceEntityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesPriceEntityType) IsValid() bool {
	for _, existing := range AllowedTypesPriceEntityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.PriceEntityType value
func (v TypesPriceEntityType) Ptr() *TypesPriceEntityType {
	return &v
}

type NullableTypesPriceEntityType struct {
	value *TypesPriceEntityType
	isSet bool
}

func (v NullableTypesPriceEntityType) Get() *TypesPriceEntityType {
	return v.value
}

func (v *NullableTypesPriceEntityType) Set(val *TypesPriceEntityType) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesPriceEntityType) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesPriceEntityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesPriceEntityType(val *TypesPriceEntityType) *NullableTypesPriceEntityType {
	return &NullableTypesPriceEntityType{value: val, isSet: true}
}

func (v NullableTypesPriceEntityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesPriceEntityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

