/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoDeleteSubscriptionLineItemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoDeleteSubscriptionLineItemRequest{}

// DtoDeleteSubscriptionLineItemRequest struct for DtoDeleteSubscriptionLineItemRequest
type DtoDeleteSubscriptionLineItemRequest struct {
	EffectiveFrom *string `json:"effective_from,omitempty"`
}

// NewDtoDeleteSubscriptionLineItemRequest instantiates a new DtoDeleteSubscriptionLineItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoDeleteSubscriptionLineItemRequest() *DtoDeleteSubscriptionLineItemRequest {
	this := DtoDeleteSubscriptionLineItemRequest{}
	return &this
}

// NewDtoDeleteSubscriptionLineItemRequestWithDefaults instantiates a new DtoDeleteSubscriptionLineItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoDeleteSubscriptionLineItemRequestWithDefaults() *DtoDeleteSubscriptionLineItemRequest {
	this := DtoDeleteSubscriptionLineItemRequest{}
	return &this
}

// GetEffectiveFrom returns the EffectiveFrom field value if set, zero value otherwise.
func (o *DtoDeleteSubscriptionLineItemRequest) GetEffectiveFrom() string {
	if o == nil || IsNil(o.EffectiveFrom) {
		var ret string
		return ret
	}
	return *o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoDeleteSubscriptionLineItemRequest) GetEffectiveFromOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveFrom) {
		return nil, false
	}
	return o.EffectiveFrom, true
}

// HasEffectiveFrom returns a boolean if a field has been set.
func (o *DtoDeleteSubscriptionLineItemRequest) HasEffectiveFrom() bool {
	if o != nil && !IsNil(o.EffectiveFrom) {
		return true
	}

	return false
}

// SetEffectiveFrom gets a reference to the given string and assigns it to the EffectiveFrom field.
func (o *DtoDeleteSubscriptionLineItemRequest) SetEffectiveFrom(v string) {
	o.EffectiveFrom = &v
}

func (o DtoDeleteSubscriptionLineItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoDeleteSubscriptionLineItemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EffectiveFrom) {
		toSerialize["effective_from"] = o.EffectiveFrom
	}
	return toSerialize, nil
}

type NullableDtoDeleteSubscriptionLineItemRequest struct {
	value *DtoDeleteSubscriptionLineItemRequest
	isSet bool
}

func (v NullableDtoDeleteSubscriptionLineItemRequest) Get() *DtoDeleteSubscriptionLineItemRequest {
	return v.value
}

func (v *NullableDtoDeleteSubscriptionLineItemRequest) Set(val *DtoDeleteSubscriptionLineItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoDeleteSubscriptionLineItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoDeleteSubscriptionLineItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoDeleteSubscriptionLineItemRequest(val *DtoDeleteSubscriptionLineItemRequest) *NullableDtoDeleteSubscriptionLineItemRequest {
	return &NullableDtoDeleteSubscriptionLineItemRequest{value: val, isSet: true}
}

func (v NullableDtoDeleteSubscriptionLineItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoDeleteSubscriptionLineItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


