/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoCreateCostsheetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateCostsheetResponse{}

// DtoCreateCostsheetResponse struct for DtoCreateCostsheetResponse
type DtoCreateCostsheetResponse struct {
	Costsheet *DtoCostsheetResponse `json:"costsheet,omitempty"`
}

// NewDtoCreateCostsheetResponse instantiates a new DtoCreateCostsheetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateCostsheetResponse() *DtoCreateCostsheetResponse {
	this := DtoCreateCostsheetResponse{}
	return &this
}

// NewDtoCreateCostsheetResponseWithDefaults instantiates a new DtoCreateCostsheetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateCostsheetResponseWithDefaults() *DtoCreateCostsheetResponse {
	this := DtoCreateCostsheetResponse{}
	return &this
}

// GetCostsheet returns the Costsheet field value if set, zero value otherwise.
func (o *DtoCreateCostsheetResponse) GetCostsheet() DtoCostsheetResponse {
	if o == nil || IsNil(o.Costsheet) {
		var ret DtoCostsheetResponse
		return ret
	}
	return *o.Costsheet
}

// GetCostsheetOk returns a tuple with the Costsheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateCostsheetResponse) GetCostsheetOk() (*DtoCostsheetResponse, bool) {
	if o == nil || IsNil(o.Costsheet) {
		return nil, false
	}
	return o.Costsheet, true
}

// HasCostsheet returns a boolean if a field has been set.
func (o *DtoCreateCostsheetResponse) HasCostsheet() bool {
	if o != nil && !IsNil(o.Costsheet) {
		return true
	}

	return false
}

// SetCostsheet gets a reference to the given DtoCostsheetResponse and assigns it to the Costsheet field.
func (o *DtoCreateCostsheetResponse) SetCostsheet(v DtoCostsheetResponse) {
	o.Costsheet = &v
}

func (o DtoCreateCostsheetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateCostsheetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Costsheet) {
		toSerialize["costsheet"] = o.Costsheet
	}
	return toSerialize, nil
}

type NullableDtoCreateCostsheetResponse struct {
	value *DtoCreateCostsheetResponse
	isSet bool
}

func (v NullableDtoCreateCostsheetResponse) Get() *DtoCreateCostsheetResponse {
	return v.value
}

func (v *NullableDtoCreateCostsheetResponse) Set(val *DtoCreateCostsheetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateCostsheetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateCostsheetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateCostsheetResponse(val *DtoCreateCostsheetResponse) *NullableDtoCreateCostsheetResponse {
	return &NullableDtoCreateCostsheetResponse{value: val, isSet: true}
}

func (v NullableDtoCreateCostsheetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateCostsheetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


