/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoListConnectionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoListConnectionsResponse{}

// DtoListConnectionsResponse struct for DtoListConnectionsResponse
type DtoListConnectionsResponse struct {
	Connections []DtoConnectionResponse `json:"connections,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewDtoListConnectionsResponse instantiates a new DtoListConnectionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoListConnectionsResponse() *DtoListConnectionsResponse {
	this := DtoListConnectionsResponse{}
	return &this
}

// NewDtoListConnectionsResponseWithDefaults instantiates a new DtoListConnectionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoListConnectionsResponseWithDefaults() *DtoListConnectionsResponse {
	this := DtoListConnectionsResponse{}
	return &this
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *DtoListConnectionsResponse) GetConnections() []DtoConnectionResponse {
	if o == nil || IsNil(o.Connections) {
		var ret []DtoConnectionResponse
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListConnectionsResponse) GetConnectionsOk() ([]DtoConnectionResponse, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *DtoListConnectionsResponse) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []DtoConnectionResponse and assigns it to the Connections field.
func (o *DtoListConnectionsResponse) SetConnections(v []DtoConnectionResponse) {
	o.Connections = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *DtoListConnectionsResponse) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListConnectionsResponse) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *DtoListConnectionsResponse) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *DtoListConnectionsResponse) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *DtoListConnectionsResponse) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListConnectionsResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *DtoListConnectionsResponse) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *DtoListConnectionsResponse) SetOffset(v int32) {
	o.Offset = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *DtoListConnectionsResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListConnectionsResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *DtoListConnectionsResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *DtoListConnectionsResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o DtoListConnectionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoListConnectionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableDtoListConnectionsResponse struct {
	value *DtoListConnectionsResponse
	isSet bool
}

func (v NullableDtoListConnectionsResponse) Get() *DtoListConnectionsResponse {
	return v.value
}

func (v *NullableDtoListConnectionsResponse) Set(val *DtoListConnectionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoListConnectionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoListConnectionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoListConnectionsResponse(val *DtoListConnectionsResponse) *NullableDtoListConnectionsResponse {
	return &NullableDtoListConnectionsResponse{value: val, isSet: true}
}

func (v NullableDtoListConnectionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoListConnectionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


