/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DtoSubscriptionChangeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoSubscriptionChangeRequest{}

// DtoSubscriptionChangeRequest Request object for changing a subscription plan (upgrade/downgrade)
type DtoSubscriptionChangeRequest struct {
	BillingCadence TypesBillingCadence `json:"billing_cadence"`
	BillingCycle TypesBillingCycle `json:"billing_cycle"`
	BillingPeriod TypesBillingPeriod `json:"billing_period"`
	// billing_period_count is the billing period count for the new subscription
	BillingPeriodCount *int32 `json:"billing_period_count,omitempty"`
	// metadata contains additional key-value pairs for storing extra information
	Metadata *map[string]string `json:"metadata,omitempty"`
	ProrationBehavior TypesProrationBehavior `json:"proration_behavior"`
	// target_plan_id is the ID of the new plan to change to (required)
	TargetPlanId string `json:"target_plan_id"`
}

type _DtoSubscriptionChangeRequest DtoSubscriptionChangeRequest

// NewDtoSubscriptionChangeRequest instantiates a new DtoSubscriptionChangeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoSubscriptionChangeRequest(billingCadence TypesBillingCadence, billingCycle TypesBillingCycle, billingPeriod TypesBillingPeriod, prorationBehavior TypesProrationBehavior, targetPlanId string) *DtoSubscriptionChangeRequest {
	this := DtoSubscriptionChangeRequest{}
	this.BillingCadence = billingCadence
	this.BillingCycle = billingCycle
	this.BillingPeriod = billingPeriod
	this.ProrationBehavior = prorationBehavior
	this.TargetPlanId = targetPlanId
	return &this
}

// NewDtoSubscriptionChangeRequestWithDefaults instantiates a new DtoSubscriptionChangeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoSubscriptionChangeRequestWithDefaults() *DtoSubscriptionChangeRequest {
	this := DtoSubscriptionChangeRequest{}
	return &this
}

// GetBillingCadence returns the BillingCadence field value
func (o *DtoSubscriptionChangeRequest) GetBillingCadence() TypesBillingCadence {
	if o == nil {
		var ret TypesBillingCadence
		return ret
	}

	return o.BillingCadence
}

// GetBillingCadenceOk returns a tuple with the BillingCadence field value
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetBillingCadenceOk() (*TypesBillingCadence, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCadence, true
}

// SetBillingCadence sets field value
func (o *DtoSubscriptionChangeRequest) SetBillingCadence(v TypesBillingCadence) {
	o.BillingCadence = v
}

// GetBillingCycle returns the BillingCycle field value
func (o *DtoSubscriptionChangeRequest) GetBillingCycle() TypesBillingCycle {
	if o == nil {
		var ret TypesBillingCycle
		return ret
	}

	return o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetBillingCycleOk() (*TypesBillingCycle, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCycle, true
}

// SetBillingCycle sets field value
func (o *DtoSubscriptionChangeRequest) SetBillingCycle(v TypesBillingCycle) {
	o.BillingCycle = v
}

// GetBillingPeriod returns the BillingPeriod field value
func (o *DtoSubscriptionChangeRequest) GetBillingPeriod() TypesBillingPeriod {
	if o == nil {
		var ret TypesBillingPeriod
		return ret
	}

	return o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetBillingPeriodOk() (*TypesBillingPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingPeriod, true
}

// SetBillingPeriod sets field value
func (o *DtoSubscriptionChangeRequest) SetBillingPeriod(v TypesBillingPeriod) {
	o.BillingPeriod = v
}

// GetBillingPeriodCount returns the BillingPeriodCount field value if set, zero value otherwise.
func (o *DtoSubscriptionChangeRequest) GetBillingPeriodCount() int32 {
	if o == nil || IsNil(o.BillingPeriodCount) {
		var ret int32
		return ret
	}
	return *o.BillingPeriodCount
}

// GetBillingPeriodCountOk returns a tuple with the BillingPeriodCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetBillingPeriodCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingPeriodCount) {
		return nil, false
	}
	return o.BillingPeriodCount, true
}

// HasBillingPeriodCount returns a boolean if a field has been set.
func (o *DtoSubscriptionChangeRequest) HasBillingPeriodCount() bool {
	if o != nil && !IsNil(o.BillingPeriodCount) {
		return true
	}

	return false
}

// SetBillingPeriodCount gets a reference to the given int32 and assigns it to the BillingPeriodCount field.
func (o *DtoSubscriptionChangeRequest) SetBillingPeriodCount(v int32) {
	o.BillingPeriodCount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DtoSubscriptionChangeRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DtoSubscriptionChangeRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DtoSubscriptionChangeRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetProrationBehavior returns the ProrationBehavior field value
func (o *DtoSubscriptionChangeRequest) GetProrationBehavior() TypesProrationBehavior {
	if o == nil {
		var ret TypesProrationBehavior
		return ret
	}

	return o.ProrationBehavior
}

// GetProrationBehaviorOk returns a tuple with the ProrationBehavior field value
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetProrationBehaviorOk() (*TypesProrationBehavior, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProrationBehavior, true
}

// SetProrationBehavior sets field value
func (o *DtoSubscriptionChangeRequest) SetProrationBehavior(v TypesProrationBehavior) {
	o.ProrationBehavior = v
}

// GetTargetPlanId returns the TargetPlanId field value
func (o *DtoSubscriptionChangeRequest) GetTargetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPlanId
}

// GetTargetPlanIdOk returns a tuple with the TargetPlanId field value
// and a boolean to check if the value has been set.
func (o *DtoSubscriptionChangeRequest) GetTargetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPlanId, true
}

// SetTargetPlanId sets field value
func (o *DtoSubscriptionChangeRequest) SetTargetPlanId(v string) {
	o.TargetPlanId = v
}

func (o DtoSubscriptionChangeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoSubscriptionChangeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["billing_cadence"] = o.BillingCadence
	toSerialize["billing_cycle"] = o.BillingCycle
	toSerialize["billing_period"] = o.BillingPeriod
	if !IsNil(o.BillingPeriodCount) {
		toSerialize["billing_period_count"] = o.BillingPeriodCount
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["proration_behavior"] = o.ProrationBehavior
	toSerialize["target_plan_id"] = o.TargetPlanId
	return toSerialize, nil
}

func (o *DtoSubscriptionChangeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"billing_cadence",
		"billing_cycle",
		"billing_period",
		"proration_behavior",
		"target_plan_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoSubscriptionChangeRequest := _DtoSubscriptionChangeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoSubscriptionChangeRequest)

	if err != nil {
		return err
	}

	*o = DtoSubscriptionChangeRequest(varDtoSubscriptionChangeRequest)

	return err
}

type NullableDtoSubscriptionChangeRequest struct {
	value *DtoSubscriptionChangeRequest
	isSet bool
}

func (v NullableDtoSubscriptionChangeRequest) Get() *DtoSubscriptionChangeRequest {
	return v.value
}

func (v *NullableDtoSubscriptionChangeRequest) Set(val *DtoSubscriptionChangeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoSubscriptionChangeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoSubscriptionChangeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoSubscriptionChangeRequest(val *DtoSubscriptionChangeRequest) *NullableDtoSubscriptionChangeRequest {
	return &NullableDtoSubscriptionChangeRequest{value: val, isSet: true}
}

func (v NullableDtoSubscriptionChangeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoSubscriptionChangeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


