/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexpriceclient

import (
	"encoding/json"
)

// checks if the DtoCustomerUsageSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCustomerUsageSummaryResponse{}

// DtoCustomerUsageSummaryResponse struct for DtoCustomerUsageSummaryResponse
type DtoCustomerUsageSummaryResponse struct {
	CustomerId *string `json:"customer_id,omitempty"`
	Features []DtoFeatureUsageSummary `json:"features,omitempty"`
	Pagination *TypesPaginationResponse `json:"pagination,omitempty"`
	Period *DtoBillingPeriodInfo `json:"period,omitempty"`
}

// NewDtoCustomerUsageSummaryResponse instantiates a new DtoCustomerUsageSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCustomerUsageSummaryResponse() *DtoCustomerUsageSummaryResponse {
	this := DtoCustomerUsageSummaryResponse{}
	return &this
}

// NewDtoCustomerUsageSummaryResponseWithDefaults instantiates a new DtoCustomerUsageSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCustomerUsageSummaryResponseWithDefaults() *DtoCustomerUsageSummaryResponse {
	this := DtoCustomerUsageSummaryResponse{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *DtoCustomerUsageSummaryResponse) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCustomerUsageSummaryResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *DtoCustomerUsageSummaryResponse) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *DtoCustomerUsageSummaryResponse) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *DtoCustomerUsageSummaryResponse) GetFeatures() []DtoFeatureUsageSummary {
	if o == nil || IsNil(o.Features) {
		var ret []DtoFeatureUsageSummary
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCustomerUsageSummaryResponse) GetFeaturesOk() ([]DtoFeatureUsageSummary, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *DtoCustomerUsageSummaryResponse) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []DtoFeatureUsageSummary and assigns it to the Features field.
func (o *DtoCustomerUsageSummaryResponse) SetFeatures(v []DtoFeatureUsageSummary) {
	o.Features = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DtoCustomerUsageSummaryResponse) GetPagination() TypesPaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret TypesPaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCustomerUsageSummaryResponse) GetPaginationOk() (*TypesPaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DtoCustomerUsageSummaryResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given TypesPaginationResponse and assigns it to the Pagination field.
func (o *DtoCustomerUsageSummaryResponse) SetPagination(v TypesPaginationResponse) {
	o.Pagination = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *DtoCustomerUsageSummaryResponse) GetPeriod() DtoBillingPeriodInfo {
	if o == nil || IsNil(o.Period) {
		var ret DtoBillingPeriodInfo
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCustomerUsageSummaryResponse) GetPeriodOk() (*DtoBillingPeriodInfo, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *DtoCustomerUsageSummaryResponse) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given DtoBillingPeriodInfo and assigns it to the Period field.
func (o *DtoCustomerUsageSummaryResponse) SetPeriod(v DtoBillingPeriodInfo) {
	o.Period = &v
}

func (o DtoCustomerUsageSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCustomerUsageSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableDtoCustomerUsageSummaryResponse struct {
	value *DtoCustomerUsageSummaryResponse
	isSet bool
}

func (v NullableDtoCustomerUsageSummaryResponse) Get() *DtoCustomerUsageSummaryResponse {
	return v.value
}

func (v *NullableDtoCustomerUsageSummaryResponse) Set(val *DtoCustomerUsageSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCustomerUsageSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCustomerUsageSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCustomerUsageSummaryResponse(val *DtoCustomerUsageSummaryResponse) *NullableDtoCustomerUsageSummaryResponse {
	return &NullableDtoCustomerUsageSummaryResponse{value: val, isSet: true}
}

func (v NullableDtoCustomerUsageSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCustomerUsageSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


