/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoInvoiceLineItemPreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoInvoiceLineItemPreview{}

// DtoInvoiceLineItemPreview struct for DtoInvoiceLineItemPreview
type DtoInvoiceLineItemPreview struct {
	// amount for this line item
	Amount *string `json:"amount,omitempty"`
	// description of the line item
	Description *string `json:"description,omitempty"`
	// is_proration indicates if this line item is a proration
	IsProration *bool `json:"is_proration,omitempty"`
	// period_end for this line item (if applicable)
	PeriodEnd *string `json:"period_end,omitempty"`
	// period_start for this line item (if applicable)
	PeriodStart *string `json:"period_start,omitempty"`
	// quantity for this line item
	Quantity *string `json:"quantity,omitempty"`
	// unit_price for this line item
	UnitPrice *string `json:"unit_price,omitempty"`
}

// NewDtoInvoiceLineItemPreview instantiates a new DtoInvoiceLineItemPreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoInvoiceLineItemPreview() *DtoInvoiceLineItemPreview {
	this := DtoInvoiceLineItemPreview{}
	return &this
}

// NewDtoInvoiceLineItemPreviewWithDefaults instantiates a new DtoInvoiceLineItemPreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoInvoiceLineItemPreviewWithDefaults() *DtoInvoiceLineItemPreview {
	this := DtoInvoiceLineItemPreview{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *DtoInvoiceLineItemPreview) SetAmount(v string) {
	o.Amount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DtoInvoiceLineItemPreview) SetDescription(v string) {
	o.Description = &v
}

// GetIsProration returns the IsProration field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetIsProration() bool {
	if o == nil || IsNil(o.IsProration) {
		var ret bool
		return ret
	}
	return *o.IsProration
}

// GetIsProrationOk returns a tuple with the IsProration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetIsProrationOk() (*bool, bool) {
	if o == nil || IsNil(o.IsProration) {
		return nil, false
	}
	return o.IsProration, true
}

// HasIsProration returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasIsProration() bool {
	if o != nil && !IsNil(o.IsProration) {
		return true
	}

	return false
}

// SetIsProration gets a reference to the given bool and assigns it to the IsProration field.
func (o *DtoInvoiceLineItemPreview) SetIsProration(v bool) {
	o.IsProration = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetPeriodEnd() string {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret string
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetPeriodEndOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given string and assigns it to the PeriodEnd field.
func (o *DtoInvoiceLineItemPreview) SetPeriodEnd(v string) {
	o.PeriodEnd = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetPeriodStart() string {
	if o == nil || IsNil(o.PeriodStart) {
		var ret string
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetPeriodStartOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given string and assigns it to the PeriodStart field.
func (o *DtoInvoiceLineItemPreview) SetPeriodStart(v string) {
	o.PeriodStart = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetQuantity() string {
	if o == nil || IsNil(o.Quantity) {
		var ret string
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given string and assigns it to the Quantity field.
func (o *DtoInvoiceLineItemPreview) SetQuantity(v string) {
	o.Quantity = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *DtoInvoiceLineItemPreview) GetUnitPrice() string {
	if o == nil || IsNil(o.UnitPrice) {
		var ret string
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoInvoiceLineItemPreview) GetUnitPriceOk() (*string, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *DtoInvoiceLineItemPreview) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given string and assigns it to the UnitPrice field.
func (o *DtoInvoiceLineItemPreview) SetUnitPrice(v string) {
	o.UnitPrice = &v
}

func (o DtoInvoiceLineItemPreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoInvoiceLineItemPreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsProration) {
		toSerialize["is_proration"] = o.IsProration
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["period_end"] = o.PeriodEnd
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["period_start"] = o.PeriodStart
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unit_price"] = o.UnitPrice
	}
	return toSerialize, nil
}

type NullableDtoInvoiceLineItemPreview struct {
	value *DtoInvoiceLineItemPreview
	isSet bool
}

func (v NullableDtoInvoiceLineItemPreview) Get() *DtoInvoiceLineItemPreview {
	return v.value
}

func (v *NullableDtoInvoiceLineItemPreview) Set(val *DtoInvoiceLineItemPreview) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoInvoiceLineItemPreview) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoInvoiceLineItemPreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoInvoiceLineItemPreview(val *DtoInvoiceLineItemPreview) *NullableDtoInvoiceLineItemPreview {
	return &NullableDtoInvoiceLineItemPreview{value: val, isSet: true}
}

func (v NullableDtoInvoiceLineItemPreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoInvoiceLineItemPreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


