/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoCancelSubscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCancelSubscriptionResponse{}

// DtoCancelSubscriptionResponse struct for DtoCancelSubscriptionResponse
type DtoCancelSubscriptionResponse struct {
	CancellationType *TypesCancellationType `json:"cancellation_type,omitempty"`
	EffectiveDate *string `json:"effective_date,omitempty"`
	// Response metadata
	Message *string `json:"message,omitempty"`
	ProcessedAt *string `json:"processed_at,omitempty"`
	ProrationDetails []DtoProrationDetail `json:"proration_details,omitempty"`
	ProrationInvoice *DtoInvoiceResponse `json:"proration_invoice,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Status *TypesSubscriptionStatus `json:"status,omitempty"`
	// Basic cancellation info
	SubscriptionId *string `json:"subscription_id,omitempty"`
	TotalCreditAmount *string `json:"total_credit_amount,omitempty"`
}

// NewDtoCancelSubscriptionResponse instantiates a new DtoCancelSubscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCancelSubscriptionResponse() *DtoCancelSubscriptionResponse {
	this := DtoCancelSubscriptionResponse{}
	return &this
}

// NewDtoCancelSubscriptionResponseWithDefaults instantiates a new DtoCancelSubscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCancelSubscriptionResponseWithDefaults() *DtoCancelSubscriptionResponse {
	this := DtoCancelSubscriptionResponse{}
	return &this
}

// GetCancellationType returns the CancellationType field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetCancellationType() TypesCancellationType {
	if o == nil || IsNil(o.CancellationType) {
		var ret TypesCancellationType
		return ret
	}
	return *o.CancellationType
}

// GetCancellationTypeOk returns a tuple with the CancellationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetCancellationTypeOk() (*TypesCancellationType, bool) {
	if o == nil || IsNil(o.CancellationType) {
		return nil, false
	}
	return o.CancellationType, true
}

// HasCancellationType returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasCancellationType() bool {
	if o != nil && !IsNil(o.CancellationType) {
		return true
	}

	return false
}

// SetCancellationType gets a reference to the given TypesCancellationType and assigns it to the CancellationType field.
func (o *DtoCancelSubscriptionResponse) SetCancellationType(v TypesCancellationType) {
	o.CancellationType = &v
}

// GetEffectiveDate returns the EffectiveDate field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetEffectiveDate() string {
	if o == nil || IsNil(o.EffectiveDate) {
		var ret string
		return ret
	}
	return *o.EffectiveDate
}

// GetEffectiveDateOk returns a tuple with the EffectiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetEffectiveDateOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveDate) {
		return nil, false
	}
	return o.EffectiveDate, true
}

// HasEffectiveDate returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasEffectiveDate() bool {
	if o != nil && !IsNil(o.EffectiveDate) {
		return true
	}

	return false
}

// SetEffectiveDate gets a reference to the given string and assigns it to the EffectiveDate field.
func (o *DtoCancelSubscriptionResponse) SetEffectiveDate(v string) {
	o.EffectiveDate = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoCancelSubscriptionResponse) SetMessage(v string) {
	o.Message = &v
}

// GetProcessedAt returns the ProcessedAt field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetProcessedAt() string {
	if o == nil || IsNil(o.ProcessedAt) {
		var ret string
		return ret
	}
	return *o.ProcessedAt
}

// GetProcessedAtOk returns a tuple with the ProcessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetProcessedAtOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessedAt) {
		return nil, false
	}
	return o.ProcessedAt, true
}

// HasProcessedAt returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasProcessedAt() bool {
	if o != nil && !IsNil(o.ProcessedAt) {
		return true
	}

	return false
}

// SetProcessedAt gets a reference to the given string and assigns it to the ProcessedAt field.
func (o *DtoCancelSubscriptionResponse) SetProcessedAt(v string) {
	o.ProcessedAt = &v
}

// GetProrationDetails returns the ProrationDetails field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetProrationDetails() []DtoProrationDetail {
	if o == nil || IsNil(o.ProrationDetails) {
		var ret []DtoProrationDetail
		return ret
	}
	return o.ProrationDetails
}

// GetProrationDetailsOk returns a tuple with the ProrationDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetProrationDetailsOk() ([]DtoProrationDetail, bool) {
	if o == nil || IsNil(o.ProrationDetails) {
		return nil, false
	}
	return o.ProrationDetails, true
}

// HasProrationDetails returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasProrationDetails() bool {
	if o != nil && !IsNil(o.ProrationDetails) {
		return true
	}

	return false
}

// SetProrationDetails gets a reference to the given []DtoProrationDetail and assigns it to the ProrationDetails field.
func (o *DtoCancelSubscriptionResponse) SetProrationDetails(v []DtoProrationDetail) {
	o.ProrationDetails = v
}

// GetProrationInvoice returns the ProrationInvoice field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetProrationInvoice() DtoInvoiceResponse {
	if o == nil || IsNil(o.ProrationInvoice) {
		var ret DtoInvoiceResponse
		return ret
	}
	return *o.ProrationInvoice
}

// GetProrationInvoiceOk returns a tuple with the ProrationInvoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetProrationInvoiceOk() (*DtoInvoiceResponse, bool) {
	if o == nil || IsNil(o.ProrationInvoice) {
		return nil, false
	}
	return o.ProrationInvoice, true
}

// HasProrationInvoice returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasProrationInvoice() bool {
	if o != nil && !IsNil(o.ProrationInvoice) {
		return true
	}

	return false
}

// SetProrationInvoice gets a reference to the given DtoInvoiceResponse and assigns it to the ProrationInvoice field.
func (o *DtoCancelSubscriptionResponse) SetProrationInvoice(v DtoInvoiceResponse) {
	o.ProrationInvoice = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *DtoCancelSubscriptionResponse) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetStatus() TypesSubscriptionStatus {
	if o == nil || IsNil(o.Status) {
		var ret TypesSubscriptionStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetStatusOk() (*TypesSubscriptionStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TypesSubscriptionStatus and assigns it to the Status field.
func (o *DtoCancelSubscriptionResponse) SetStatus(v TypesSubscriptionStatus) {
	o.Status = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *DtoCancelSubscriptionResponse) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetTotalCreditAmount returns the TotalCreditAmount field value if set, zero value otherwise.
func (o *DtoCancelSubscriptionResponse) GetTotalCreditAmount() string {
	if o == nil || IsNil(o.TotalCreditAmount) {
		var ret string
		return ret
	}
	return *o.TotalCreditAmount
}

// GetTotalCreditAmountOk returns a tuple with the TotalCreditAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCancelSubscriptionResponse) GetTotalCreditAmountOk() (*string, bool) {
	if o == nil || IsNil(o.TotalCreditAmount) {
		return nil, false
	}
	return o.TotalCreditAmount, true
}

// HasTotalCreditAmount returns a boolean if a field has been set.
func (o *DtoCancelSubscriptionResponse) HasTotalCreditAmount() bool {
	if o != nil && !IsNil(o.TotalCreditAmount) {
		return true
	}

	return false
}

// SetTotalCreditAmount gets a reference to the given string and assigns it to the TotalCreditAmount field.
func (o *DtoCancelSubscriptionResponse) SetTotalCreditAmount(v string) {
	o.TotalCreditAmount = &v
}

func (o DtoCancelSubscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCancelSubscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CancellationType) {
		toSerialize["cancellation_type"] = o.CancellationType
	}
	if !IsNil(o.EffectiveDate) {
		toSerialize["effective_date"] = o.EffectiveDate
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ProcessedAt) {
		toSerialize["processed_at"] = o.ProcessedAt
	}
	if !IsNil(o.ProrationDetails) {
		toSerialize["proration_details"] = o.ProrationDetails
	}
	if !IsNil(o.ProrationInvoice) {
		toSerialize["proration_invoice"] = o.ProrationInvoice
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if !IsNil(o.TotalCreditAmount) {
		toSerialize["total_credit_amount"] = o.TotalCreditAmount
	}
	return toSerialize, nil
}

type NullableDtoCancelSubscriptionResponse struct {
	value *DtoCancelSubscriptionResponse
	isSet bool
}

func (v NullableDtoCancelSubscriptionResponse) Get() *DtoCancelSubscriptionResponse {
	return v.value
}

func (v *NullableDtoCancelSubscriptionResponse) Set(val *DtoCancelSubscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCancelSubscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCancelSubscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCancelSubscriptionResponse(val *DtoCancelSubscriptionResponse) *NullableDtoCancelSubscriptionResponse {
	return &NullableDtoCancelSubscriptionResponse{value: val, isSet: true}
}

func (v NullableDtoCancelSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCancelSubscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


