/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoCreditGrantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreditGrantResponse{}

// DtoCreditGrantResponse struct for DtoCreditGrantResponse
type DtoCreditGrantResponse struct {
	Cadence *TypesCreditGrantCadence `json:"cadence,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreditGrantAnchor *string `json:"credit_grant_anchor,omitempty"`
	Credits *string `json:"credits,omitempty"`
	EndDate *string `json:"end_date,omitempty"`
	EnvironmentId *string `json:"environment_id,omitempty"`
	ExpirationDuration *int32 `json:"expiration_duration,omitempty"`
	ExpirationDurationUnit *TypesCreditGrantExpiryDurationUnit `json:"expiration_duration_unit,omitempty"`
	ExpirationType *TypesCreditGrantExpiryType `json:"expiration_type,omitempty"`
	Id *string `json:"id,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`
	Period *TypesCreditGrantPeriod `json:"period,omitempty"`
	PeriodCount *int32 `json:"period_count,omitempty"`
	PlanId *string `json:"plan_id,omitempty"`
	Priority *int32 `json:"priority,omitempty"`
	Scope *TypesCreditGrantScope `json:"scope,omitempty"`
	StartDate *string `json:"start_date,omitempty"`
	Status *TypesStatus `json:"status,omitempty"`
	SubscriptionId *string `json:"subscription_id,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
}

// NewDtoCreditGrantResponse instantiates a new DtoCreditGrantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreditGrantResponse() *DtoCreditGrantResponse {
	this := DtoCreditGrantResponse{}
	return &this
}

// NewDtoCreditGrantResponseWithDefaults instantiates a new DtoCreditGrantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreditGrantResponseWithDefaults() *DtoCreditGrantResponse {
	this := DtoCreditGrantResponse{}
	return &this
}

// GetCadence returns the Cadence field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetCadence() TypesCreditGrantCadence {
	if o == nil || IsNil(o.Cadence) {
		var ret TypesCreditGrantCadence
		return ret
	}
	return *o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetCadenceOk() (*TypesCreditGrantCadence, bool) {
	if o == nil || IsNil(o.Cadence) {
		return nil, false
	}
	return o.Cadence, true
}

// HasCadence returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasCadence() bool {
	if o != nil && !IsNil(o.Cadence) {
		return true
	}

	return false
}

// SetCadence gets a reference to the given TypesCreditGrantCadence and assigns it to the Cadence field.
func (o *DtoCreditGrantResponse) SetCadence(v TypesCreditGrantCadence) {
	o.Cadence = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DtoCreditGrantResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *DtoCreditGrantResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreditGrantAnchor returns the CreditGrantAnchor field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetCreditGrantAnchor() string {
	if o == nil || IsNil(o.CreditGrantAnchor) {
		var ret string
		return ret
	}
	return *o.CreditGrantAnchor
}

// GetCreditGrantAnchorOk returns a tuple with the CreditGrantAnchor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetCreditGrantAnchorOk() (*string, bool) {
	if o == nil || IsNil(o.CreditGrantAnchor) {
		return nil, false
	}
	return o.CreditGrantAnchor, true
}

// HasCreditGrantAnchor returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasCreditGrantAnchor() bool {
	if o != nil && !IsNil(o.CreditGrantAnchor) {
		return true
	}

	return false
}

// SetCreditGrantAnchor gets a reference to the given string and assigns it to the CreditGrantAnchor field.
func (o *DtoCreditGrantResponse) SetCreditGrantAnchor(v string) {
	o.CreditGrantAnchor = &v
}

// GetCredits returns the Credits field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetCredits() string {
	if o == nil || IsNil(o.Credits) {
		var ret string
		return ret
	}
	return *o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetCreditsOk() (*string, bool) {
	if o == nil || IsNil(o.Credits) {
		return nil, false
	}
	return o.Credits, true
}

// HasCredits returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasCredits() bool {
	if o != nil && !IsNil(o.Credits) {
		return true
	}

	return false
}

// SetCredits gets a reference to the given string and assigns it to the Credits field.
func (o *DtoCreditGrantResponse) SetCredits(v string) {
	o.Credits = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *DtoCreditGrantResponse) SetEndDate(v string) {
	o.EndDate = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetEnvironmentId() string {
	if o == nil || IsNil(o.EnvironmentId) {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentId) {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasEnvironmentId() bool {
	if o != nil && !IsNil(o.EnvironmentId) {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *DtoCreditGrantResponse) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetExpirationDuration returns the ExpirationDuration field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetExpirationDuration() int32 {
	if o == nil || IsNil(o.ExpirationDuration) {
		var ret int32
		return ret
	}
	return *o.ExpirationDuration
}

// GetExpirationDurationOk returns a tuple with the ExpirationDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetExpirationDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpirationDuration) {
		return nil, false
	}
	return o.ExpirationDuration, true
}

// HasExpirationDuration returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasExpirationDuration() bool {
	if o != nil && !IsNil(o.ExpirationDuration) {
		return true
	}

	return false
}

// SetExpirationDuration gets a reference to the given int32 and assigns it to the ExpirationDuration field.
func (o *DtoCreditGrantResponse) SetExpirationDuration(v int32) {
	o.ExpirationDuration = &v
}

// GetExpirationDurationUnit returns the ExpirationDurationUnit field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetExpirationDurationUnit() TypesCreditGrantExpiryDurationUnit {
	if o == nil || IsNil(o.ExpirationDurationUnit) {
		var ret TypesCreditGrantExpiryDurationUnit
		return ret
	}
	return *o.ExpirationDurationUnit
}

// GetExpirationDurationUnitOk returns a tuple with the ExpirationDurationUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetExpirationDurationUnitOk() (*TypesCreditGrantExpiryDurationUnit, bool) {
	if o == nil || IsNil(o.ExpirationDurationUnit) {
		return nil, false
	}
	return o.ExpirationDurationUnit, true
}

// HasExpirationDurationUnit returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasExpirationDurationUnit() bool {
	if o != nil && !IsNil(o.ExpirationDurationUnit) {
		return true
	}

	return false
}

// SetExpirationDurationUnit gets a reference to the given TypesCreditGrantExpiryDurationUnit and assigns it to the ExpirationDurationUnit field.
func (o *DtoCreditGrantResponse) SetExpirationDurationUnit(v TypesCreditGrantExpiryDurationUnit) {
	o.ExpirationDurationUnit = &v
}

// GetExpirationType returns the ExpirationType field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetExpirationType() TypesCreditGrantExpiryType {
	if o == nil || IsNil(o.ExpirationType) {
		var ret TypesCreditGrantExpiryType
		return ret
	}
	return *o.ExpirationType
}

// GetExpirationTypeOk returns a tuple with the ExpirationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetExpirationTypeOk() (*TypesCreditGrantExpiryType, bool) {
	if o == nil || IsNil(o.ExpirationType) {
		return nil, false
	}
	return o.ExpirationType, true
}

// HasExpirationType returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasExpirationType() bool {
	if o != nil && !IsNil(o.ExpirationType) {
		return true
	}

	return false
}

// SetExpirationType gets a reference to the given TypesCreditGrantExpiryType and assigns it to the ExpirationType field.
func (o *DtoCreditGrantResponse) SetExpirationType(v TypesCreditGrantExpiryType) {
	o.ExpirationType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoCreditGrantResponse) SetId(v string) {
	o.Id = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DtoCreditGrantResponse) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoCreditGrantResponse) SetName(v string) {
	o.Name = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetPeriod() TypesCreditGrantPeriod {
	if o == nil || IsNil(o.Period) {
		var ret TypesCreditGrantPeriod
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetPeriodOk() (*TypesCreditGrantPeriod, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given TypesCreditGrantPeriod and assigns it to the Period field.
func (o *DtoCreditGrantResponse) SetPeriod(v TypesCreditGrantPeriod) {
	o.Period = &v
}

// GetPeriodCount returns the PeriodCount field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetPeriodCount() int32 {
	if o == nil || IsNil(o.PeriodCount) {
		var ret int32
		return ret
	}
	return *o.PeriodCount
}

// GetPeriodCountOk returns a tuple with the PeriodCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetPeriodCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PeriodCount) {
		return nil, false
	}
	return o.PeriodCount, true
}

// HasPeriodCount returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasPeriodCount() bool {
	if o != nil && !IsNil(o.PeriodCount) {
		return true
	}

	return false
}

// SetPeriodCount gets a reference to the given int32 and assigns it to the PeriodCount field.
func (o *DtoCreditGrantResponse) SetPeriodCount(v int32) {
	o.PeriodCount = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetPlanId() string {
	if o == nil || IsNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetPlanIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *DtoCreditGrantResponse) SetPlanId(v string) {
	o.PlanId = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *DtoCreditGrantResponse) SetPriority(v int32) {
	o.Priority = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetScope() TypesCreditGrantScope {
	if o == nil || IsNil(o.Scope) {
		var ret TypesCreditGrantScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetScopeOk() (*TypesCreditGrantScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given TypesCreditGrantScope and assigns it to the Scope field.
func (o *DtoCreditGrantResponse) SetScope(v TypesCreditGrantScope) {
	o.Scope = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *DtoCreditGrantResponse) SetStartDate(v string) {
	o.StartDate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetStatus() TypesStatus {
	if o == nil || IsNil(o.Status) {
		var ret TypesStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetStatusOk() (*TypesStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TypesStatus and assigns it to the Status field.
func (o *DtoCreditGrantResponse) SetStatus(v TypesStatus) {
	o.Status = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *DtoCreditGrantResponse) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DtoCreditGrantResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DtoCreditGrantResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *DtoCreditGrantResponse) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreditGrantResponse) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *DtoCreditGrantResponse) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *DtoCreditGrantResponse) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

func (o DtoCreditGrantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreditGrantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cadence) {
		toSerialize["cadence"] = o.Cadence
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.CreditGrantAnchor) {
		toSerialize["credit_grant_anchor"] = o.CreditGrantAnchor
	}
	if !IsNil(o.Credits) {
		toSerialize["credits"] = o.Credits
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.EnvironmentId) {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	if !IsNil(o.ExpirationDuration) {
		toSerialize["expiration_duration"] = o.ExpirationDuration
	}
	if !IsNil(o.ExpirationDurationUnit) {
		toSerialize["expiration_duration_unit"] = o.ExpirationDurationUnit
	}
	if !IsNil(o.ExpirationType) {
		toSerialize["expiration_type"] = o.ExpirationType
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.PeriodCount) {
		toSerialize["period_count"] = o.PeriodCount
	}
	if !IsNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	return toSerialize, nil
}

type NullableDtoCreditGrantResponse struct {
	value *DtoCreditGrantResponse
	isSet bool
}

func (v NullableDtoCreditGrantResponse) Get() *DtoCreditGrantResponse {
	return v.value
}

func (v *NullableDtoCreditGrantResponse) Set(val *DtoCreditGrantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreditGrantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreditGrantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreditGrantResponse(val *DtoCreditGrantResponse) *NullableDtoCreditGrantResponse {
	return &NullableDtoCreditGrantResponse{value: val, isSet: true}
}

func (v NullableDtoCreditGrantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreditGrantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


