/*
FlexPrice API

FlexPrice API Service

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flexprice

import (
	"encoding/json"
)

// checks if the DtoListCreditNotesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoListCreditNotesResponse{}

// DtoListCreditNotesResponse struct for DtoListCreditNotesResponse
type DtoListCreditNotesResponse struct {
	Items []DtoCreditNoteResponse `json:"items,omitempty"`
	Pagination *TypesPaginationResponse `json:"pagination,omitempty"`
}

// NewDtoListCreditNotesResponse instantiates a new DtoListCreditNotesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoListCreditNotesResponse() *DtoListCreditNotesResponse {
	this := DtoListCreditNotesResponse{}
	return &this
}

// NewDtoListCreditNotesResponseWithDefaults instantiates a new DtoListCreditNotesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoListCreditNotesResponseWithDefaults() *DtoListCreditNotesResponse {
	this := DtoListCreditNotesResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoListCreditNotesResponse) GetItems() []DtoCreditNoteResponse {
	if o == nil || IsNil(o.Items) {
		var ret []DtoCreditNoteResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListCreditNotesResponse) GetItemsOk() ([]DtoCreditNoteResponse, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoListCreditNotesResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DtoCreditNoteResponse and assigns it to the Items field.
func (o *DtoListCreditNotesResponse) SetItems(v []DtoCreditNoteResponse) {
	o.Items = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DtoListCreditNotesResponse) GetPagination() TypesPaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret TypesPaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListCreditNotesResponse) GetPaginationOk() (*TypesPaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DtoListCreditNotesResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given TypesPaginationResponse and assigns it to the Pagination field.
func (o *DtoListCreditNotesResponse) SetPagination(v TypesPaginationResponse) {
	o.Pagination = &v
}

func (o DtoListCreditNotesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoListCreditNotesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableDtoListCreditNotesResponse struct {
	value *DtoListCreditNotesResponse
	isSet bool
}

func (v NullableDtoListCreditNotesResponse) Get() *DtoListCreditNotesResponse {
	return v.value
}

func (v *NullableDtoListCreditNotesResponse) Set(val *DtoListCreditNotesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoListCreditNotesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoListCreditNotesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoListCreditNotesResponse(val *DtoListCreditNotesResponse) *NullableDtoListCreditNotesResponse {
	return &NullableDtoListCreditNotesResponse{value: val, isSet: true}
}

func (v NullableDtoListCreditNotesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoListCreditNotesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


