// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type DeleteAPIKeySecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (d DeleteAPIKeySecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeySecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeySecurityOption1) GetAPIKeyAuth() string {
	if d == nil {
		return ""
	}
	return d.APIKeyAuth
}

// #region class-body-deleteapikeysecurityoption1
// #endregion class-body-deleteapikeysecurityoption1

type DeleteAPIKeySecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (d DeleteAPIKeySecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeySecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeySecurityOption2) GetAPIKeyAuth() string {
	if d == nil {
		return ""
	}
	return d.APIKeyAuth
}

// #region class-body-deleteapikeysecurityoption2
// #endregion class-body-deleteapikeysecurityoption2

type DeleteAPIKeySecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (d DeleteAPIKeySecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeySecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeySecurityOption3) GetBearerAuth() string {
	if d == nil {
		return ""
	}
	return d.BearerAuth
}

func (d *DeleteAPIKeySecurityOption3) GetEnvironmentID() string {
	if d == nil {
		return ""
	}
	return d.EnvironmentID
}

// #region class-body-deleteapikeysecurityoption3
// #endregion class-body-deleteapikeysecurityoption3

type DeleteAPIKeySecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (d DeleteAPIKeySecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeySecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeySecurityOption4) GetBearerAuth() string {
	if d == nil {
		return ""
	}
	return d.BearerAuth
}

// #region class-body-deleteapikeysecurityoption4
// #endregion class-body-deleteapikeysecurityoption4

type DeleteAPIKeySecurity struct {
	Option1 *DeleteAPIKeySecurityOption1 `security:"option"`
	Option2 *DeleteAPIKeySecurityOption2 `security:"option"`
	Option3 *DeleteAPIKeySecurityOption3 `security:"option"`
	Option4 *DeleteAPIKeySecurityOption4 `security:"option"`
}

func (d DeleteAPIKeySecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeySecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeySecurity) GetOption1() *DeleteAPIKeySecurityOption1 {
	if d == nil {
		return nil
	}
	return d.Option1
}

func (d *DeleteAPIKeySecurity) GetOption2() *DeleteAPIKeySecurityOption2 {
	if d == nil {
		return nil
	}
	return d.Option2
}

func (d *DeleteAPIKeySecurity) GetOption3() *DeleteAPIKeySecurityOption3 {
	if d == nil {
		return nil
	}
	return d.Option3
}

func (d *DeleteAPIKeySecurity) GetOption4() *DeleteAPIKeySecurityOption4 {
	if d == nil {
		return nil
	}
	return d.Option4
}

type DeleteAPIKeyRequest struct {
	// API key ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d DeleteAPIKeyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeyRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAPIKeyResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
}

func (d DeleteAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAPIKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAPIKeyResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}
