// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type GetAddonEntitlementsSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetAddonEntitlementsSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsSecurityOption1) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getaddonentitlementssecurityoption1
// #endregion class-body-getaddonentitlementssecurityoption1

type GetAddonEntitlementsSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetAddonEntitlementsSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsSecurityOption2) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getaddonentitlementssecurityoption2
// #endregion class-body-getaddonentitlementssecurityoption2

type GetAddonEntitlementsSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (g GetAddonEntitlementsSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsSecurityOption3) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

func (g *GetAddonEntitlementsSecurityOption3) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

// #region class-body-getaddonentitlementssecurityoption3
// #endregion class-body-getaddonentitlementssecurityoption3

type GetAddonEntitlementsSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g GetAddonEntitlementsSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsSecurityOption4) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

// #region class-body-getaddonentitlementssecurityoption4
// #endregion class-body-getaddonentitlementssecurityoption4

type GetAddonEntitlementsSecurity struct {
	Option1 *GetAddonEntitlementsSecurityOption1 `security:"option"`
	Option2 *GetAddonEntitlementsSecurityOption2 `security:"option"`
	Option3 *GetAddonEntitlementsSecurityOption3 `security:"option"`
	Option4 *GetAddonEntitlementsSecurityOption4 `security:"option"`
}

func (g GetAddonEntitlementsSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsSecurity) GetOption1() *GetAddonEntitlementsSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetAddonEntitlementsSecurity) GetOption2() *GetAddonEntitlementsSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

func (g *GetAddonEntitlementsSecurity) GetOption3() *GetAddonEntitlementsSecurityOption3 {
	if g == nil {
		return nil
	}
	return g.Option3
}

func (g *GetAddonEntitlementsSecurity) GetOption4() *GetAddonEntitlementsSecurityOption4 {
	if g == nil {
		return nil
	}
	return g.Option4
}

type GetAddonEntitlementsRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetAddonEntitlementsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetAddonEntitlementsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListEntitlementsResponse *types.ListEntitlementsResponse
}

func (g GetAddonEntitlementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonEntitlementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonEntitlementsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAddonEntitlementsResponse) GetListEntitlementsResponse() *types.ListEntitlementsResponse {
	if g == nil {
		return nil
	}
	return g.ListEntitlementsResponse
}
