// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type GetCreditGrantSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetCreditGrantSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantSecurityOption1) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getcreditgrantsecurityoption1
// #endregion class-body-getcreditgrantsecurityoption1

type GetCreditGrantSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetCreditGrantSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantSecurityOption2) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getcreditgrantsecurityoption2
// #endregion class-body-getcreditgrantsecurityoption2

type GetCreditGrantSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (g GetCreditGrantSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantSecurityOption3) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

func (g *GetCreditGrantSecurityOption3) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

// #region class-body-getcreditgrantsecurityoption3
// #endregion class-body-getcreditgrantsecurityoption3

type GetCreditGrantSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g GetCreditGrantSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantSecurityOption4) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

// #region class-body-getcreditgrantsecurityoption4
// #endregion class-body-getcreditgrantsecurityoption4

type GetCreditGrantSecurity struct {
	Option1 *GetCreditGrantSecurityOption1 `security:"option"`
	Option2 *GetCreditGrantSecurityOption2 `security:"option"`
	Option3 *GetCreditGrantSecurityOption3 `security:"option"`
	Option4 *GetCreditGrantSecurityOption4 `security:"option"`
}

func (g GetCreditGrantSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantSecurity) GetOption1() *GetCreditGrantSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetCreditGrantSecurity) GetOption2() *GetCreditGrantSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

func (g *GetCreditGrantSecurity) GetOption3() *GetCreditGrantSecurityOption3 {
	if g == nil {
		return nil
	}
	return g.Option3
}

func (g *GetCreditGrantSecurity) GetOption4() *GetCreditGrantSecurityOption4 {
	if g == nil {
		return nil
	}
	return g.Option4
}

type GetCreditGrantRequest struct {
	// Credit Grant ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetCreditGrantRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCreditGrantResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CreditGrantResponse *types.CreditGrantResponse
}

func (g GetCreditGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditGrantResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCreditGrantResponse) GetCreditGrantResponse() *types.CreditGrantResponse {
	if g == nil {
		return nil
	}
	return g.CreditGrantResponse
}
