// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type GetPaymentSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetPaymentSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentSecurityOption1) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getpaymentsecurityoption1
// #endregion class-body-getpaymentsecurityoption1

type GetPaymentSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetPaymentSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentSecurityOption2) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getpaymentsecurityoption2
// #endregion class-body-getpaymentsecurityoption2

type GetPaymentSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (g GetPaymentSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentSecurityOption3) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

func (g *GetPaymentSecurityOption3) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

// #region class-body-getpaymentsecurityoption3
// #endregion class-body-getpaymentsecurityoption3

type GetPaymentSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g GetPaymentSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentSecurityOption4) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

// #region class-body-getpaymentsecurityoption4
// #endregion class-body-getpaymentsecurityoption4

type GetPaymentSecurity struct {
	Option1 *GetPaymentSecurityOption1 `security:"option"`
	Option2 *GetPaymentSecurityOption2 `security:"option"`
	Option3 *GetPaymentSecurityOption3 `security:"option"`
	Option4 *GetPaymentSecurityOption4 `security:"option"`
}

func (g GetPaymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentSecurity) GetOption1() *GetPaymentSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetPaymentSecurity) GetOption2() *GetPaymentSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

func (g *GetPaymentSecurity) GetOption3() *GetPaymentSecurityOption3 {
	if g == nil {
		return nil
	}
	return g.Option3
}

func (g *GetPaymentSecurity) GetOption4() *GetPaymentSecurityOption4 {
	if g == nil {
		return nil
	}
	return g.Option4
}

type GetPaymentRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetPaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPaymentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Payment details
	PaymentResponse *types.PaymentResponse
}

func (g GetPaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPaymentResponse) GetPaymentResponse() *types.PaymentResponse {
	if g == nil {
		return nil
	}
	return g.PaymentResponse
}
