// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type GetScheduledTaskSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetScheduledTaskSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskSecurityOption1) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getscheduledtasksecurityoption1
// #endregion class-body-getscheduledtasksecurityoption1

type GetScheduledTaskSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetScheduledTaskSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskSecurityOption2) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getscheduledtasksecurityoption2
// #endregion class-body-getscheduledtasksecurityoption2

type GetScheduledTaskSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (g GetScheduledTaskSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskSecurityOption3) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

func (g *GetScheduledTaskSecurityOption3) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

// #region class-body-getscheduledtasksecurityoption3
// #endregion class-body-getscheduledtasksecurityoption3

type GetScheduledTaskSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g GetScheduledTaskSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskSecurityOption4) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

// #region class-body-getscheduledtasksecurityoption4
// #endregion class-body-getscheduledtasksecurityoption4

type GetScheduledTaskSecurity struct {
	Option1 *GetScheduledTaskSecurityOption1 `security:"option"`
	Option2 *GetScheduledTaskSecurityOption2 `security:"option"`
	Option3 *GetScheduledTaskSecurityOption3 `security:"option"`
	Option4 *GetScheduledTaskSecurityOption4 `security:"option"`
}

func (g GetScheduledTaskSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskSecurity) GetOption1() *GetScheduledTaskSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetScheduledTaskSecurity) GetOption2() *GetScheduledTaskSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

func (g *GetScheduledTaskSecurity) GetOption3() *GetScheduledTaskSecurityOption3 {
	if g == nil {
		return nil
	}
	return g.Option3
}

func (g *GetScheduledTaskSecurity) GetOption4() *GetScheduledTaskSecurityOption4 {
	if g == nil {
		return nil
	}
	return g.Option4
}

type GetScheduledTaskRequest struct {
	// Scheduled Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetScheduledTaskRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetScheduledTaskResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ScheduledTaskResponse *types.ScheduledTaskResponse
}

func (g GetScheduledTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetScheduledTaskResponse) GetScheduledTaskResponse() *types.ScheduledTaskResponse {
	if g == nil {
		return nil
	}
	return g.ScheduledTaskResponse
}
