// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type GetSubscriptionV2SecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetSubscriptionV2SecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2SecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2SecurityOption1) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getsubscriptionv2securityoption1
// #endregion class-body-getsubscriptionv2securityoption1

type GetSubscriptionV2SecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (g GetSubscriptionV2SecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2SecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2SecurityOption2) GetAPIKeyAuth() string {
	if g == nil {
		return ""
	}
	return g.APIKeyAuth
}

// #region class-body-getsubscriptionv2securityoption2
// #endregion class-body-getsubscriptionv2securityoption2

type GetSubscriptionV2SecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (g GetSubscriptionV2SecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2SecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2SecurityOption3) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

func (g *GetSubscriptionV2SecurityOption3) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

// #region class-body-getsubscriptionv2securityoption3
// #endregion class-body-getsubscriptionv2securityoption3

type GetSubscriptionV2SecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g GetSubscriptionV2SecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2SecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2SecurityOption4) GetBearerAuth() string {
	if g == nil {
		return ""
	}
	return g.BearerAuth
}

// #region class-body-getsubscriptionv2securityoption4
// #endregion class-body-getsubscriptionv2securityoption4

type GetSubscriptionV2Security struct {
	Option1 *GetSubscriptionV2SecurityOption1 `security:"option"`
	Option2 *GetSubscriptionV2SecurityOption2 `security:"option"`
	Option3 *GetSubscriptionV2SecurityOption3 `security:"option"`
	Option4 *GetSubscriptionV2SecurityOption4 `security:"option"`
}

func (g GetSubscriptionV2Security) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2Security) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2Security) GetOption1() *GetSubscriptionV2SecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetSubscriptionV2Security) GetOption2() *GetSubscriptionV2SecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

func (g *GetSubscriptionV2Security) GetOption3() *GetSubscriptionV2SecurityOption3 {
	if g == nil {
		return nil
	}
	return g.Option3
}

func (g *GetSubscriptionV2Security) GetOption4() *GetSubscriptionV2SecurityOption4 {
	if g == nil {
		return nil
	}
	return g.Option4
}

// #region class-body-getsubscriptionv2security
// #endregion class-body-getsubscriptionv2security

type GetSubscriptionV2Request struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Comma-separated list of fields to expand (e.g., 'subscription_line_items,prices,plan')
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

func (g GetSubscriptionV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetSubscriptionV2Request) GetExpand() *string {
	if g == nil {
		return nil
	}
	return g.Expand
}

// #region class-body-getsubscriptionv2request
// #endregion class-body-getsubscriptionv2request

type GetSubscriptionV2Response struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionResponseV2 *types.SubscriptionResponseV2
}

func (g GetSubscriptionV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2Response) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionV2Response) GetSubscriptionResponseV2() *types.SubscriptionResponseV2 {
	if g == nil {
		return nil
	}
	return g.SubscriptionResponseV2
}

// #region class-body-getsubscriptionv2response
// #endregion class-body-getsubscriptionv2response
