// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type QueryAlertLogSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (q QueryAlertLogSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogSecurityOption1) GetAPIKeyAuth() string {
	if q == nil {
		return ""
	}
	return q.APIKeyAuth
}

// #region class-body-queryalertlogsecurityoption1
// #endregion class-body-queryalertlogsecurityoption1

type QueryAlertLogSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (q QueryAlertLogSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogSecurityOption2) GetAPIKeyAuth() string {
	if q == nil {
		return ""
	}
	return q.APIKeyAuth
}

// #region class-body-queryalertlogsecurityoption2
// #endregion class-body-queryalertlogsecurityoption2

type QueryAlertLogSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (q QueryAlertLogSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogSecurityOption3) GetBearerAuth() string {
	if q == nil {
		return ""
	}
	return q.BearerAuth
}

func (q *QueryAlertLogSecurityOption3) GetEnvironmentID() string {
	if q == nil {
		return ""
	}
	return q.EnvironmentID
}

// #region class-body-queryalertlogsecurityoption3
// #endregion class-body-queryalertlogsecurityoption3

type QueryAlertLogSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (q QueryAlertLogSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogSecurityOption4) GetBearerAuth() string {
	if q == nil {
		return ""
	}
	return q.BearerAuth
}

// #region class-body-queryalertlogsecurityoption4
// #endregion class-body-queryalertlogsecurityoption4

type QueryAlertLogSecurity struct {
	Option1 *QueryAlertLogSecurityOption1 `security:"option"`
	Option2 *QueryAlertLogSecurityOption2 `security:"option"`
	Option3 *QueryAlertLogSecurityOption3 `security:"option"`
	Option4 *QueryAlertLogSecurityOption4 `security:"option"`
}

func (q QueryAlertLogSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogSecurity) GetOption1() *QueryAlertLogSecurityOption1 {
	if q == nil {
		return nil
	}
	return q.Option1
}

func (q *QueryAlertLogSecurity) GetOption2() *QueryAlertLogSecurityOption2 {
	if q == nil {
		return nil
	}
	return q.Option2
}

func (q *QueryAlertLogSecurity) GetOption3() *QueryAlertLogSecurityOption3 {
	if q == nil {
		return nil
	}
	return q.Option3
}

func (q *QueryAlertLogSecurity) GetOption4() *QueryAlertLogSecurityOption4 {
	if q == nil {
		return nil
	}
	return q.Option4
}

type QueryAlertLogResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListAlertLogsResponse *types.ListAlertLogsResponse
}

func (q QueryAlertLogResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryAlertLogResponse) GetListAlertLogsResponse() *types.ListAlertLogsResponse {
	if q == nil {
		return nil
	}
	return q.ListAlertLogsResponse
}
