// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type QueryAlertSettingsSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (q QueryAlertSettingsSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsSecurityOption1) GetAPIKeyAuth() string {
	if q == nil {
		return ""
	}
	return q.APIKeyAuth
}

// #region class-body-queryalertsettingssecurityoption1
// #endregion class-body-queryalertsettingssecurityoption1

type QueryAlertSettingsSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (q QueryAlertSettingsSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsSecurityOption2) GetAPIKeyAuth() string {
	if q == nil {
		return ""
	}
	return q.APIKeyAuth
}

// #region class-body-queryalertsettingssecurityoption2
// #endregion class-body-queryalertsettingssecurityoption2

type QueryAlertSettingsSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (q QueryAlertSettingsSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsSecurityOption3) GetBearerAuth() string {
	if q == nil {
		return ""
	}
	return q.BearerAuth
}

func (q *QueryAlertSettingsSecurityOption3) GetEnvironmentID() string {
	if q == nil {
		return ""
	}
	return q.EnvironmentID
}

// #region class-body-queryalertsettingssecurityoption3
// #endregion class-body-queryalertsettingssecurityoption3

type QueryAlertSettingsSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (q QueryAlertSettingsSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsSecurityOption4) GetBearerAuth() string {
	if q == nil {
		return ""
	}
	return q.BearerAuth
}

// #region class-body-queryalertsettingssecurityoption4
// #endregion class-body-queryalertsettingssecurityoption4

type QueryAlertSettingsSecurity struct {
	Option1 *QueryAlertSettingsSecurityOption1 `security:"option"`
	Option2 *QueryAlertSettingsSecurityOption2 `security:"option"`
	Option3 *QueryAlertSettingsSecurityOption3 `security:"option"`
	Option4 *QueryAlertSettingsSecurityOption4 `security:"option"`
}

func (q QueryAlertSettingsSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsSecurity) GetOption1() *QueryAlertSettingsSecurityOption1 {
	if q == nil {
		return nil
	}
	return q.Option1
}

func (q *QueryAlertSettingsSecurity) GetOption2() *QueryAlertSettingsSecurityOption2 {
	if q == nil {
		return nil
	}
	return q.Option2
}

func (q *QueryAlertSettingsSecurity) GetOption3() *QueryAlertSettingsSecurityOption3 {
	if q == nil {
		return nil
	}
	return q.Option3
}

func (q *QueryAlertSettingsSecurity) GetOption4() *QueryAlertSettingsSecurityOption4 {
	if q == nil {
		return nil
	}
	return q.Option4
}

type QueryAlertSettingsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListAlertSettingsResponse *types.ListAlertSettingsResponse
}

func (q QueryAlertSettingsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertSettingsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertSettingsResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryAlertSettingsResponse) GetListAlertSettingsResponse() *types.ListAlertSettingsResponse {
	if q == nil {
		return nil
	}
	return q.ListAlertSettingsResponse
}
