// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"github.com/flexprice/go-sdk/v2/models/types"
)

type TerminateWalletSecurityOption1 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (t TerminateWalletSecurityOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletSecurityOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletSecurityOption1) GetAPIKeyAuth() string {
	if t == nil {
		return ""
	}
	return t.APIKeyAuth
}

// #region class-body-terminatewalletsecurityoption1
// #endregion class-body-terminatewalletsecurityoption1

type TerminateWalletSecurityOption2 struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
}

func (t TerminateWalletSecurityOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletSecurityOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"ApiKeyAuth"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletSecurityOption2) GetAPIKeyAuth() string {
	if t == nil {
		return ""
	}
	return t.APIKeyAuth
}

// #region class-body-terminatewalletsecurityoption2
// #endregion class-body-terminatewalletsecurityoption2

type TerminateWalletSecurityOption3 struct {
	BearerAuth    string `security:"scheme,type=http,subtype=bearer,composite,name=Authorization"`
	EnvironmentID string `security:"scheme,type=apiKey,subtype=header,composite,name=X-Environment-ID"`
}

func (t TerminateWalletSecurityOption3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletSecurityOption3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"BearerAuth", "EnvironmentId"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletSecurityOption3) GetBearerAuth() string {
	if t == nil {
		return ""
	}
	return t.BearerAuth
}

func (t *TerminateWalletSecurityOption3) GetEnvironmentID() string {
	if t == nil {
		return ""
	}
	return t.EnvironmentID
}

// #region class-body-terminatewalletsecurityoption3
// #endregion class-body-terminatewalletsecurityoption3

type TerminateWalletSecurityOption4 struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (t TerminateWalletSecurityOption4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletSecurityOption4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"BearerAuth"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletSecurityOption4) GetBearerAuth() string {
	if t == nil {
		return ""
	}
	return t.BearerAuth
}

// #region class-body-terminatewalletsecurityoption4
// #endregion class-body-terminatewalletsecurityoption4

type TerminateWalletSecurity struct {
	Option1 *TerminateWalletSecurityOption1 `security:"option"`
	Option2 *TerminateWalletSecurityOption2 `security:"option"`
	Option3 *TerminateWalletSecurityOption3 `security:"option"`
	Option4 *TerminateWalletSecurityOption4 `security:"option"`
}

func (t TerminateWalletSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletSecurity) GetOption1() *TerminateWalletSecurityOption1 {
	if t == nil {
		return nil
	}
	return t.Option1
}

func (t *TerminateWalletSecurity) GetOption2() *TerminateWalletSecurityOption2 {
	if t == nil {
		return nil
	}
	return t.Option2
}

func (t *TerminateWalletSecurity) GetOption3() *TerminateWalletSecurityOption3 {
	if t == nil {
		return nil
	}
	return t.Option3
}

func (t *TerminateWalletSecurity) GetOption4() *TerminateWalletSecurityOption4 {
	if t == nil {
		return nil
	}
	return t.Option4
}

type TerminateWalletRequest struct {
	// Wallet ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (t TerminateWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

type TerminateWalletResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	WalletResponse *types.WalletResponse
}

func (t TerminateWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (t *TerminateWalletResponse) GetHTTPMeta() types.HTTPMetadata {
	if t == nil {
		return types.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TerminateWalletResponse) GetWalletResponse() *types.WalletResponse {
	if t == nil {
		return nil
	}
	return t.WalletResponse
}
