// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
)

type DtoCreateUserResponse struct {
	// Empty for service accounts
	Email    *string            `json:"email,omitzero"`
	ID       *string            `json:"id,omitzero"`
	Password *string            `json:"password,omitzero"`
	Roles    []string           `json:"roles,omitzero"`
	Tenant   *DtoTenantResponse `json:"tenant,omitzero"`
	Type     *UserType          `json:"type,omitzero"`
}

func (d DtoCreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoCreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoCreateUserResponse) GetEmail() *string {
	if d == nil {
		return nil
	}
	return d.Email
}

func (d *DtoCreateUserResponse) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DtoCreateUserResponse) GetPassword() *string {
	if d == nil {
		return nil
	}
	return d.Password
}

func (d *DtoCreateUserResponse) GetRoles() []string {
	if d == nil {
		return nil
	}
	return d.Roles
}

func (d *DtoCreateUserResponse) GetTenant() *DtoTenantResponse {
	if d == nil {
		return nil
	}
	return d.Tenant
}

func (d *DtoCreateUserResponse) GetType() *UserType {
	if d == nil {
		return nil
	}
	return d.Type
}
