// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
	"time"
)

type Invoice struct {
	// adjustment_amount is the total sum of credit notes of type "adjustment".
	// These are non-cash reductions applied to the invoice (e.g. goodwill credit, billing correction).
	AdjustmentAmount *string `json:"adjustment_amount,omitzero"`
	// amount_due is the total amount that needs to be paid for this invoice
	AmountDue *string `json:"amount_due,omitzero"`
	// amount_paid is the amount that has already been paid towards this invoice
	AmountPaid *string `json:"amount_paid,omitzero"`
	// amount_remaining is the outstanding amount still owed on this invoice (calculated as amount_due minus amount_paid)
	AmountRemaining *string `json:"amount_remaining,omitzero"`
	// billing_period describes the billing period this invoice covers (e.g., "January 2024", "Q1 2024")
	BillingPeriod *string `json:"billing_period,omitzero"`
	// billing_reason indicates why this invoice was generated (e.g., "subscription_billing", "manual_charge")
	BillingReason *string `json:"billing_reason,omitzero"`
	// billing_sequence is the sequential number indicating the billing cycle for subscription invoices
	BillingSequence *int64 `json:"billing_sequence,omitzero"`
	// coupon_applications contains the coupon applications associated with this invoice (overrides embedded field)
	CouponApplications []CouponApplicationResponse `json:"coupon_applications,omitzero"`
	CreatedAt          *time.Time                  `json:"created_at,omitzero"`
	CreatedBy          *string                     `json:"created_by,omitzero"`
	// currency is the three-letter ISO currency code (e.g., USD, EUR, GBP) that applies to all monetary amounts on this invoice
	Currency *string `json:"currency,omitzero"`
	// Customer response object containing all customer information
	Customer *Customer1 `json:"customer,omitzero"`
	// customer_id is the ID of the customer who will receive this invoice
	CustomerID *string `json:"customer_id,omitzero"`
	// description is an optional description or notes about this invoice
	Description *string `json:"description,omitzero"`
	// due_date is the date when payment for this invoice is due
	DueDate *time.Time `json:"due_date,omitzero"`
	// environment_id is the ID of the environment this invoice belongs to (for multi-environment setups)
	EnvironmentID *string `json:"environment_id,omitzero"`
	// finalized_at is the timestamp when this invoice was finalized and made ready for payment
	FinalizedAt *time.Time `json:"finalized_at,omitzero"`
	// id is the unique identifier for this invoice
	ID *string `json:"id,omitzero"`
	// idempotency_key is a unique key used to prevent duplicate invoice creation when retrying API calls
	IdempotencyKey *string `json:"idempotency_key,omitzero"`
	// invoice_number is the human-readable invoice number displayed to customers (e.g., INV-2024-001)
	InvoiceNumber *string `json:"invoice_number,omitzero"`
	// invoice_pdf_url is the URL where customers can download the PDF version of this invoice
	InvoicePdfURL *string        `json:"invoice_pdf_url,omitzero"`
	InvoiceStatus *InvoiceStatus `json:"invoice_status,omitzero"`
	InvoiceType   *InvoiceType   `json:"invoice_type,omitzero"`
	// last_computed_at is the timestamp when this invoice was last computed by ComputeInvoice
	LastComputedAt *time.Time `json:"last_computed_at,omitzero"`
	// line_items contains the individual items that make up this invoice (overrides embedded field)
	LineItems []InvoiceLineItemResponse `json:"line_items,omitzero"`
	Metadata  map[string]string         `json:"metadata,omitzero"`
	// overpaid_amount is the amount overpaid if payment_status is OVERPAID (amount_paid - total)
	OverpaidAmount *string `json:"overpaid_amount,omitzero"`
	// paid_at is the timestamp when this invoice was fully paid
	PaidAt        *time.Time     `json:"paid_at,omitzero"`
	PaymentStatus *PaymentStatus `json:"payment_status,omitzero"`
	// period_end is the end date of the billing period covered by this invoice
	PeriodEnd *time.Time `json:"period_end,omitzero"`
	// period_start is the start date of the billing period covered by this invoice
	PeriodStart *time.Time `json:"period_start,omitzero"`
	// recalculated_invoice_id is the ID of the replacement invoice created when this invoice was voided and recalculated.
	// When set, it forms a parent→child link from this (voided) invoice to the new replacement invoice.
	RecalculatedInvoiceID *string `json:"recalculated_invoice_id,omitzero"`
	// refunded_amount is the total sum of credit notes of type "refund".
	// These are actual refunds issued to the customer.
	RefundedAmount *string       `json:"refunded_amount,omitzero"`
	Status         *Status       `json:"status,omitzero"`
	Subscription   *Subscription `json:"subscription,omitzero"`
	// subscription_id is the ID of the subscription this invoice is associated with (only present for subscription-based invoices)
	SubscriptionID *string `json:"subscription_id,omitzero"`
	// subtotal is the sum of all line items before any taxes, discounts, or additional fees
	Subtotal *string `json:"subtotal,omitzero"`
	// tax_applied_records contains the tax applied records associated with this invoice
	Taxes    []TaxAppliedResponse `json:"taxes,omitzero"`
	TenantID *string              `json:"tenant_id,omitzero"`
	// total is the final amount including taxes, fees, and discounts
	Total *string `json:"total,omitzero"`
	// total_discount is the sum of all coupon discounts applied to the invoice
	TotalDiscount *string `json:"total_discount,omitzero"`
	// total_prepaid_credits_applied is the total amount of prepaid credits applied to this invoice.
	TotalPrepaidCreditsApplied *string `json:"total_prepaid_credits_applied,omitzero"`
	// total_tax is the sum of all taxes combined at the invoice level.
	TotalTax  *string    `json:"total_tax,omitzero"`
	UpdatedAt *time.Time `json:"updated_at,omitzero"`
	UpdatedBy *string    `json:"updated_by,omitzero"`
	// version is the version number for tracking changes to this invoice
	Version *int64 `json:"version,omitzero"`
	// voided_at is the timestamp when this invoice was voided or cancelled
	VoidedAt *time.Time `json:"voided_at,omitzero"`
}

func (i Invoice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Invoice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Invoice) GetAdjustmentAmount() *string {
	if i == nil {
		return nil
	}
	return i.AdjustmentAmount
}

func (i *Invoice) GetAmountDue() *string {
	if i == nil {
		return nil
	}
	return i.AmountDue
}

func (i *Invoice) GetAmountPaid() *string {
	if i == nil {
		return nil
	}
	return i.AmountPaid
}

func (i *Invoice) GetAmountRemaining() *string {
	if i == nil {
		return nil
	}
	return i.AmountRemaining
}

func (i *Invoice) GetBillingPeriod() *string {
	if i == nil {
		return nil
	}
	return i.BillingPeriod
}

func (i *Invoice) GetBillingReason() *string {
	if i == nil {
		return nil
	}
	return i.BillingReason
}

func (i *Invoice) GetBillingSequence() *int64 {
	if i == nil {
		return nil
	}
	return i.BillingSequence
}

func (i *Invoice) GetCouponApplications() []CouponApplicationResponse {
	if i == nil {
		return nil
	}
	return i.CouponApplications
}

func (i *Invoice) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *Invoice) GetCreatedBy() *string {
	if i == nil {
		return nil
	}
	return i.CreatedBy
}

func (i *Invoice) GetCurrency() *string {
	if i == nil {
		return nil
	}
	return i.Currency
}

func (i *Invoice) GetCustomer() *Customer1 {
	if i == nil {
		return nil
	}
	return i.Customer
}

func (i *Invoice) GetCustomerID() *string {
	if i == nil {
		return nil
	}
	return i.CustomerID
}

func (i *Invoice) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *Invoice) GetDueDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.DueDate
}

func (i *Invoice) GetEnvironmentID() *string {
	if i == nil {
		return nil
	}
	return i.EnvironmentID
}

func (i *Invoice) GetFinalizedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.FinalizedAt
}

func (i *Invoice) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *Invoice) GetIdempotencyKey() *string {
	if i == nil {
		return nil
	}
	return i.IdempotencyKey
}

func (i *Invoice) GetInvoiceNumber() *string {
	if i == nil {
		return nil
	}
	return i.InvoiceNumber
}

func (i *Invoice) GetInvoicePdfURL() *string {
	if i == nil {
		return nil
	}
	return i.InvoicePdfURL
}

func (i *Invoice) GetInvoiceStatus() *InvoiceStatus {
	if i == nil {
		return nil
	}
	return i.InvoiceStatus
}

func (i *Invoice) GetInvoiceType() *InvoiceType {
	if i == nil {
		return nil
	}
	return i.InvoiceType
}

func (i *Invoice) GetLastComputedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.LastComputedAt
}

func (i *Invoice) GetLineItems() []InvoiceLineItemResponse {
	if i == nil {
		return nil
	}
	return i.LineItems
}

func (i *Invoice) GetMetadata() map[string]string {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *Invoice) GetOverpaidAmount() *string {
	if i == nil {
		return nil
	}
	return i.OverpaidAmount
}

func (i *Invoice) GetPaidAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.PaidAt
}

func (i *Invoice) GetPaymentStatus() *PaymentStatus {
	if i == nil {
		return nil
	}
	return i.PaymentStatus
}

func (i *Invoice) GetPeriodEnd() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodEnd
}

func (i *Invoice) GetPeriodStart() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodStart
}

func (i *Invoice) GetRecalculatedInvoiceID() *string {
	if i == nil {
		return nil
	}
	return i.RecalculatedInvoiceID
}

func (i *Invoice) GetRefundedAmount() *string {
	if i == nil {
		return nil
	}
	return i.RefundedAmount
}

func (i *Invoice) GetStatus() *Status {
	if i == nil {
		return nil
	}
	return i.Status
}

func (i *Invoice) GetSubscription() *Subscription {
	if i == nil {
		return nil
	}
	return i.Subscription
}

func (i *Invoice) GetSubscriptionID() *string {
	if i == nil {
		return nil
	}
	return i.SubscriptionID
}

func (i *Invoice) GetSubtotal() *string {
	if i == nil {
		return nil
	}
	return i.Subtotal
}

func (i *Invoice) GetTaxes() []TaxAppliedResponse {
	if i == nil {
		return nil
	}
	return i.Taxes
}

func (i *Invoice) GetTenantID() *string {
	if i == nil {
		return nil
	}
	return i.TenantID
}

func (i *Invoice) GetTotal() *string {
	if i == nil {
		return nil
	}
	return i.Total
}

func (i *Invoice) GetTotalDiscount() *string {
	if i == nil {
		return nil
	}
	return i.TotalDiscount
}

func (i *Invoice) GetTotalPrepaidCreditsApplied() *string {
	if i == nil {
		return nil
	}
	return i.TotalPrepaidCreditsApplied
}

func (i *Invoice) GetTotalTax() *string {
	if i == nil {
		return nil
	}
	return i.TotalTax
}

func (i *Invoice) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *Invoice) GetUpdatedBy() *string {
	if i == nil {
		return nil
	}
	return i.UpdatedBy
}

func (i *Invoice) GetVersion() *int64 {
	if i == nil {
		return nil
	}
	return i.Version
}

func (i *Invoice) GetVoidedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.VoidedAt
}
