// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/flexprice/go-sdk/v2/internal/utils"
)

type MeterUsageQueryResponse struct {
	AggregationType *AggregationType  `json:"aggregation_type,omitzero"`
	EventCount      *int64            `json:"event_count,omitzero"`
	MeterID         *string           `json:"meter_id,omitzero"`
	Points          []MeterUsagePoint `json:"points,omitzero"`
	TotalValue      *string           `json:"total_value,omitzero"`
}

func (m MeterUsageQueryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeterUsageQueryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MeterUsageQueryResponse) GetAggregationType() *AggregationType {
	if m == nil {
		return nil
	}
	return m.AggregationType
}

func (m *MeterUsageQueryResponse) GetEventCount() *int64 {
	if m == nil {
		return nil
	}
	return m.EventCount
}

func (m *MeterUsageQueryResponse) GetMeterID() *string {
	if m == nil {
		return nil
	}
	return m.MeterID
}

func (m *MeterUsageQueryResponse) GetPoints() []MeterUsagePoint {
	if m == nil {
		return nil
	}
	return m.Points
}

func (m *MeterUsageQueryResponse) GetTotalValue() *string {
	if m == nil {
		return nil
	}
	return m.TotalValue
}
